// Code generated by genmodule. DO NOT EDIT.
//
// Regen: standard gen module --tag contoh --pkg contoh --apply
//
// Berkas ini masih BOLEH ditulis ulang. Begitu modulnya dikawinkan tangan, bekukan modulnya:
// namanya berubah dari handler.gen.go jadi handler.go dan generator berhenti menyentuhnya (B-03).

package contoh

import (
	"context"

	contohgen "example.test/fixture/apps/api/internal/gen/contoh"
	"example.test/fixture/apps/api/internal/platform/appcontext"
	"example.test/fixture/apps/api/internal/platform/dtoconv"
)

// handler memegang service dan mengimplementasikan server ketat hasil generate.
//
// Ia SATU-SATUNYA lapis yang menyebut tipe generated (B-01). Tugasnya persis dua: membongkar
// RequestObject jadi argumen bertipe internal, dan membungkus hasil internal jadi respons
// generated. Nol penulisan respons mentah (B-02) — respons ditulis lapis generated dari nilai yang
// dikembalikan, dan galat naik sebagai error untuk dipetakan middleware terpusat lewat hook di
// Mount.
type handler struct{ svc *service }

var _ contohgen.StrictServerInterface = (*handler)(nil)

// Konteks penyewa dibaca lewat appcontext.From(ctx) — SATU pengambilan dari context.Context yang server
// ketat berikan, tanpa type-assert ke tipe konteks kerangka kerja HTTP lebih dulu. Assert semacam
// itu bekerja hanya karena generator kebetulan meneruskan konteks aslinya apa adanya, dan itu tidak
// dijanjikan dokumen mana pun.
//
// Kalau modul ini kelak butuh konteks kerangka kerja sungguhan (badan mentah, header, multipart),
// tambahkan pengambilnya sendiri SESUDAH pembekuan — bukan di kerangka ini, karena mayoritas
// operasi tidak membutuhkannya dan impor yang tak terpakai adalah galat kompilasi.

// GetContoh melayani GET /contoh.
func (h *handler) GetContoh(ctx context.Context, request contohgen.GetContohRequestObject) (contohgen.GetContohResponseObject, error) {
	data, pg, err := h.svc.GetContoh(appcontext.From(ctx), dtoGetContohParamsFromWire(request.Params))
	if err != nil {
		return nil, err
	}
	var out contohgen.GetContoh200JSONResponse
	out.Message = "Success"
	out.Data = dtoconv.Slice(data, func(v dtoContoh) contohgen.Contoh { return v.toWire() })
	out.MetaData = contohgen.ContohMetaData{Pagination: contohgen.Pagination{Page: pg.Page, Limit: pg.Limit, Total: pg.Total, TotalPages: pg.TotalPages}}
	return out, nil
}

// GetContohById melayani GET /contoh/{contohId}.
func (h *handler) GetContohById(ctx context.Context, request contohgen.GetContohByIdRequestObject) (contohgen.GetContohByIdResponseObject, error) {
	data, err := h.svc.GetContohById(appcontext.From(ctx), request.ContohId)
	if err != nil {
		return nil, err
	}
	var out contohgen.GetContohById200JSONResponse
	out.Message = "Success"
	out.Data = data.toWire()
	return out, nil
}

// PostContoh melayani POST /contoh.
func (h *handler) PostContoh(ctx context.Context, request contohgen.PostContohRequestObject) (contohgen.PostContohResponseObject, error) {
	data, err := h.svc.PostContoh(appcontext.From(ctx), dtoconv.Ptr(request.Body, dtoContohCreateRequestFromWire))
	if err != nil {
		return nil, err
	}
	var out contohgen.PostContoh201JSONResponse
	out.Message = "Success"
	out.Data = data.toWire()
	return out, nil
}
