// Alat genmodule — bangkitkan KERANGKA empat berkas sebuah modul feature dari kontrak:
//
//	register.<gen>   Register() -> <pkg>gen.Mount, store di-inject nil
//	handler.<gen>    impl StrictServerInterface; memetakan tipe generated <-> tipe internal
//	service.<gen>    delegasi tipis handler -> store
//	repository.<gen> interface `store`, seluruhnya bertipe INTERNAL
//
// Yang TIDAK dibangkitkan: lapis KUERI. Itu satu-satunya berkas yang menyimpan pengetahuan yang
// tidak ada di kontrak — SQL, join, dan terutama predikat penyewa (T-01: batas penyewa hidup di
// predikat kueri dan tidak bisa diturunkan dari kontrak). Karena itu ia ditulis tangan, dan
// sampai ia ada `Register` menyuntikkan `nil` sebagai store: modulnya kompilasi dan ikut boot,
// tapi setiap operasinya PANIC bila dipanggil. Itu keadaan yang disengaja dan TERLIHAT, bukan
// setengah jadi yang diam.
//
// # Sumber kebenaran: AST Go yang sudah digenerate, bukan bundel YAML
//
// Alat ini membaca berkas generated di `<genDir>/<pkg>` dengan go/parser, sama seperti gendto.
// Bukan bundel OpenAPI-nya. Alasannya sempit: nama tipe Go yang harus ditulis di keluaran
// (GetXParams, XCreateRequest, GetX200JSONResponse) adalah keputusan generator kode, bukan
// keputusan kontrak. Menurunkannya ulang dari YAML berarti menyalin aturan penamaan generator ke
// sini lalu berharap keduanya tidak pernah menyimpang. Membaca keluarannya membuat kelas itu
// tidak bisa ada.
//
// # Pembekuan: NAMA BERKAS yang jadi keadaannya, buku besar yang jadi klaimnya
//
// Sesudah kerangka ini dikawinkan dengan tangan (dependensi disuntik, validasi ditambahkan,
// perilaku per-operasi diperbaiki), modulnya TIDAK BOLEH digenerate ulang — generator tidak tahu
// dependensi apa yang disuntikkan atau proses apa yang ditambahkan di level service, dan menulis
// ulang berkasnya akan menghapusnya tanpa suara (B-03). `-freeze` menandai transisi itu dengan
// mengganti nama `<dasar><genSuffix>` -> `<dasar>.go`, dan sejak itu generator MENOLAK menyentuh
// modulnya.
//
// Keadaannya terbaca dari DISK — ada tidaknya berkas kerangka tanpa sufiks generated — bukan
// dari sebuah daftar. Daftar bisa menyimpang dari kenyataan; nama berkas tidak bisa. Buku besar
// modul terpasang adalah KLAIM atas keadaan itu, yang gate periksa dua arah (G-05).
//
//	genmodule [-config <jalur>] [-messages <dir>] -tag <TAG> -pkg <PKG> [-feature <DIR>] [-out <DIR>] [-apply] [-force]
//	genmodule [-config <jalur>] -pkg <PKG> [-feature <DIR>] -freeze [-apply]
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"engineering-baseline/tooling/internal/cfg"
)

// kunciDipakai: setiap kunci katalog yang bisa dicetak alat ini, termasuk yang ditulis sebagai
// komentar ke DALAM kode hasil. Diperiksa di muka lewat Katalog.Lengkap — uji paritas sisi
// TypeScript hanya membandingkan id.json dengan en.json, jadi kunci yang lupa ditambahkan di
// KEDUA berkas lolos dari sana.
var kunciDipakai = []string{
	"config.tidak_ditemukan",
	"gen.dry_run",
	"gen.modul_beku",
	"genmodule.bendera.apply",
	"genmodule.bendera.config",
	"genmodule.bendera.feature",
	"genmodule.bendera.force",
	"genmodule.bendera.freeze",
	"genmodule.bendera.messages",
	"genmodule.bendera.out",
	"genmodule.bendera.pkg",
	"genmodule.bendera.tag",
	"genmodule.baris_berkas",
	"genmodule.baris_checklist",
	"genmodule.baris_modul",
	"genmodule.beku_baris",
	"genmodule.beku_judul",
	"genmodule.beku_sesudah",
	"genmodule.beku_tabrakan",
	"genmodule.beku_tanpa_gen",
	"genmodule.cermin_tak_terurai",
	"genmodule.gagal_buat_dir",
	"genmodule.gagal_format",
	"genmodule.gagal_tulis",
	"genmodule.gen_tak_terbaca",
	"genmodule.kawin_tangan",
	"genmodule.komentar.handler",
	"genmodule.komentar.handler_ctx",
	"genmodule.komentar.header",
	"genmodule.komentar.operasi",
	"genmodule.komentar.register",
	"genmodule.komentar.service",
	"genmodule.komentar.service_new",
	"genmodule.komentar.store",
	"genmodule.meta_bentuk_lain",
	"genmodule.meta_bukan_ident",
	"genmodule.meta_tipe_hilang",
	"genmodule.pemakaian",
	"genmodule.pkg_wajib",
	"genmodule.sufiks_menabrak_beku",
	"genmodule.tag_wajib",
	"genmodule.tanpa_respons_sukses",
	"genmodule.tanpa_strict_server",
	"genmodule.tenancy.checklist",
	"genmodule.tenancy.metode",
}

// penandaGenerated TIDAK diterjemahkan dan tidak masuk katalog. Ia bukan prosa untuk manusia
// melainkan penanda MESIN: gofmt, linter, dan penghitung diff mengenalinya lewat pola tetap
// `^// Code generated .* DO NOT EDIT\.$`. Menerjemahkannya membuat berkas hasil berhenti
// dikenali sebagai generated di setiap alat itu.
const penandaGenerated = "// Code generated by genmodule. DO NOT EDIT."

// berkasKerangka adalah keempat berkas yang alat ini miliki, dalam urutan tulis. Daftar yang
// sama dipakai deteksi beku: kehadiran salah satu nama ini TANPA sufiks generated berarti
// modulnya sudah dikawinkan tangan.
var berkasKerangka = []string{"register", "handler", "service", "repository"}

// namaChecklistTenancy: berkas KELIMA, dan sengaja BUKAN .go — lihat checklistTenancy.
const namaChecklistTenancy = "repository_tenancy_test.contoh.md"

// konstStatusSukses adalah konstanta `status: "success"` yang dipakai SELURUH respons sukses.
//
// SATU nama untuk semua operasi, dan itu hanya benar kalau `status` diangkat jadi skema BERNAMA
// di envelope bersama (C-01). Enum inline kehilangan namanya saat `allOf` diratakan, dan
// generator lalu melahirkan satu tipe enum per operasi.
//
// Kehadirannya tetap DIPERIKSA per paket, tidak diasumsikan: paket dari tag yang belum opt-in
// envelope tidak punya konstanta ini, dan menuliskannya di sana menghasilkan Go yang tidak
// kompilasi.
const konstStatusSukses = "SuccessStatusSuccess"

// Dua ketergantungan pihak ketiga yang kerangka `register` sebut — dan satu-satunya dua di
// seluruh alat ini yang TIDAK datang dari config.
//
// Alasannya bukan kelalaian: bentuk pendaftaran modul (apa yang titik masuk aplikasi oper ke
// `Register`) adalah keputusan APLIKASI, bukan keputusan kontrak, jadi tidak ada tempat di
// kontrak maupun di config yang bisa menurunkannya. Ia dinyatakan di sini sebagai konvensi
// standar ini, sejajar dengan nama paket lapis platform di cfg — dan ia satu-satunya bagian
// keluaran yang perlu disunting proyek dengan tumpukan lain. Sebut batas ini saat mengutip
// portabilitas alat ini; jangan biarkan pembaca menyimpulkan nol asumsi.
const (
	impRouter  = "github.com/gin-gonic/gin"
	tipeRouter = "RouterGroup"
	impORM     = "gorm.io/gorm"
	tipeDB     = "DB"
)

func pkgRouter() string { return path.Base(impRouter) }
func pkgORM() string    { return path.Base(impORM) }

// tipeBawaan adalah nama tipe yang BUKAN milik paket generated — ia tidak boleh diberi awalan
// alias dan tidak punya cermin internal.
var tipeBawaan = map[string]bool{
	"string": true, "bool": true, "int": true, "int32": true, "int64": true,
	"float32": true, "float64": true, "any": true, "byte": true, "error": true,
}

// benderaBernilai: bendera yang memakan argumen berikutnya. Dipakai pindaian pra-bendera supaya
// nilai sebuah bendera tidak salah dibaca sebagai bendera lain — `-pkg -h` menanyakan paket
// bernama `-h`, bukan bantuan.
var benderaBernilai = map[string]bool{
	"config": true, "messages": true, "tag": true, "pkg": true, "feature": true, "out": true,
}

type opsi struct {
	config   string
	messages string
	tag      string
	pkg      string
	feature  string
	out      string
	apply    bool
	force    bool
	freeze   bool
}

func main() {
	os.Exit(jalankan(os.Args[1:], os.Stdout, os.Stderr))
}

// jalankan adalah seluruh alat sebagai fungsi murni-cukup untuk diuji: argumen masuk, dua aliran
// keluar, satu kode keluar. main() tidak boleh punya perilaku yang tak bisa disentuh uji.
func jalankan(argv []string, keluar, galat io.Writer) int {
	praConfig, praPesan, bantuan := cfg.PraPindai(argv, benderaBernilai)

	// Bantuan dijawab SEBELUM config dimuat. Alat yang tak bisa menjelaskan dirinya sendiri
	// sebelum dikonfigurasi memaksa orang menebak bendera apa yang ada — dan yang pertama
	// menabraknya adalah orang yang baru memasang paket ini, yang belum punya config.
	if bantuan {
		return cetakBantuan(keluar, galat, praConfig, praPesan)
	}

	c, akar, err := cfg.MuatDari(praConfig)
	if err != nil {
		cfg.LaporGagalConfig(galat, praPesan, err)
		return 2
	}

	kat, err := cfg.MuatKatalogUntuk(praPesan, c.Language)
	if err != nil {
		fmt.Fprintf(galat, cfg.BootstrapKatalog+"\n", err)
		return 2
	}
	if err := kat.Lengkap(kunciDipakai); err != nil {
		fmt.Fprintf(galat, cfg.BootstrapKatalog+"\n", err)
		return 2
	}

	var o opsi
	fs := flag.NewFlagSet("genmodule", flag.ContinueOnError)
	fs.SetOutput(galat)
	daftarBendera(fs, &o, kat)
	if err := fs.Parse(argv); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		return 2
	}

	return kerjakan(c, akar, o, kat, keluar, galat)
}

func daftarBendera(fs *flag.FlagSet, o *opsi, kat cfg.Katalog) {
	fs.StringVar(&o.config, "config", "", kat.T("genmodule.bendera.config", nil))
	fs.StringVar(&o.messages, "messages", "", kat.T("genmodule.bendera.messages", nil))
	fs.StringVar(&o.tag, "tag", "", kat.T("genmodule.bendera.tag", nil))
	fs.StringVar(&o.pkg, "pkg", "", kat.T("genmodule.bendera.pkg", nil))
	fs.StringVar(&o.feature, "feature", "", kat.T("genmodule.bendera.feature", nil))
	fs.StringVar(&o.out, "out", "", kat.T("genmodule.bendera.out", nil))
	fs.BoolVar(&o.apply, "apply", false, kat.T("genmodule.bendera.apply", nil))
	fs.BoolVar(&o.force, "force", false, kat.T("genmodule.bendera.force", nil))
	fs.BoolVar(&o.freeze, "freeze", false, kat.T("genmodule.bendera.freeze", nil))
}

// cetakBantuan menjawab -h tanpa menuntut config. Kalau config KEBETULAN ketemu, bantuan dicetak
// dalam bahasa proyek itu; kalau tidak, dalam seluruh bahasa katalog — alat yang belum
// dikonfigurasi tidak tahu bahasa siapa yang benar, dan menebak salah satu sama buruknya dengan
// diam.
func cetakBantuan(keluar, galat io.Writer, praConfig, dirPesan string) int {
	bahasa := cfg.BahasaKatalog
	if c, _, err := cfg.MuatDari(praConfig); err == nil && c.Language != "" {
		bahasa = []string{c.Language}
	}
	dicetak := false
	var gagal error
	for _, b := range bahasa {
		kat, err := cfg.MuatKatalogUntuk(dirPesan, b)
		if err != nil {
			if gagal == nil {
				gagal = err
			}
			continue
		}
		if dicetak {
			fmt.Fprintln(keluar)
		}
		var o opsi
		fs := flag.NewFlagSet("genmodule", flag.ContinueOnError)
		fs.SetOutput(keluar)
		daftarBendera(fs, &o, kat)
		fmt.Fprintln(keluar, kat.T("genmodule.pemakaian", nil))
		fs.PrintDefaults()
		dicetak = true
	}
	if !dicetak {
		// Bantuan pun butuh katalog, karena teks tiap bendera ada di sana. Yang dilaporkan harus
		// SEBABNYA (katalog mana yang tak terbaca), bukan bendera yang diminta.
		fmt.Fprintf(galat, cfg.BootstrapKatalog+"\n", gagal)
		return 2
	}
	return 0
}

// ── Nama berkas dan keadaan beku ──────────────────────────────────────────────

// namaBerkas memberi nama berkas kerangka dalam keadaan TERGENERATE.
func namaBerkas(c cfg.Config, dasar string) string { return c.NamaBerkasGen(dasar) }

// namaBeku memberi nama berkas kerangka SESUDAH pembekuan. `.go` bukan nilai config: berkas Go
// yang tidak berakhiran `.go` tidak dikompilasi sama sekali.
func namaBeku(dasar string) string { return dasar + ".go" }

// sudahBeku membaca keadaan modul dari NAMA BERKAS di direktorinya, bukan dari sebuah daftar.
// Daftar bisa menyimpang dari kenyataan; nama berkas tidak bisa.
func sudahBeku(namaDiDirektori []string, c cfg.Config) bool {
	return len(berkasBeku(namaDiDirektori, c)) > 0
}

// berkasBeku melaporkan berkas kerangka mana yang sudah tanpa sufiks generated — bukti bahwa
// modulnya sudah dikawinkan tangan, dan sekaligus isi pesan penolakannya.
func berkasBeku(namaDiDirektori []string, c cfg.Config) []string {
	ada := map[string]bool{}
	for _, n := range namaDiDirektori {
		ada[n] = true
	}
	var out []string
	for _, dasar := range berkasKerangka {
		n := namaBeku(dasar)
		if n != namaBerkas(c, dasar) && ada[n] {
			out = append(out, n)
		}
	}
	return out
}

// periksaSufiks menolak genSuffix yang membuat nama tergenerate dan nama beku IDENTIK (mis.
// `.go` polos). Tanpa penjaga ini, `sudahBeku` tak akan pernah benar dan `-freeze` akan menimpa
// berkasnya sendiri — seluruh mekanisme pembekuan mati TANPA satu pesan pun. Tiap jalur
// "lewati kasus ini" adalah jalur di mana pemeriksaan tidak berjalan; jadi kasus ini tidak
// dilewati, ia dihentikan.
func periksaSufiks(c cfg.Config, kat cfg.Katalog) error {
	for _, dasar := range berkasKerangka {
		if namaBerkas(c, dasar) == namaBeku(dasar) {
			return errors.New(kat.T("genmodule.sufiks_menabrak_beku",
				map[string]string{"sufiks": c.Go.GenSuffix, "berkas": namaBeku(dasar)}))
		}
	}
	return nil
}

// namaDiDirektori mengembalikan nama berkas di sebuah direktori. Direktori yang belum ada bukan
// galat — itu justru keadaan modul yang baru pertama kali dibangkitkan.
func namaDiDirektori(dir string) ([]string, error) {
	entri, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(entri))
	for _, e := range entri {
		if !e.IsDir() {
			out = append(out, e.Name())
		}
	}
	return out, nil
}

// ── Alur ──────────────────────────────────────────────────────────────────────

func kerjakan(c cfg.Config, akar string, o opsi, kat cfg.Katalog, keluar, galat io.Writer) int {
	if err := periksaSufiks(c, kat); err != nil {
		fmt.Fprintln(galat, err)
		return 2
	}
	if o.pkg == "" {
		fmt.Fprintln(galat, kat.T("genmodule.pkg_wajib", nil))
		return 2
	}
	feat := o.feature
	if feat == "" {
		feat = o.pkg
	}
	dirFitur := filepath.Join(c.DirFeature(akar), feat)

	if o.freeze {
		return bekukan(c, kat, akar, dirFitur, feat, o.apply, keluar, galat)
	}
	if o.tag == "" {
		fmt.Fprintln(galat, kat.T("genmodule.tag_wajib", nil))
		return 2
	}

	nama, err := namaDiDirektori(dirFitur)
	if err != nil {
		fmt.Fprintln(galat, kat.T("genmodule.gagal_tulis",
			map[string]string{"jalur": dirFitur, "sebab": err.Error()}))
		return 2
	}
	if beku := berkasBeku(nama, c); len(beku) > 0 && !o.force {
		fmt.Fprintln(galat, kat.T("gen.modul_beku", map[string]string{"pkg": feat}))
		fmt.Fprintln(galat, kat.T("genmodule.kawin_tangan",
			map[string]string{"fitur": feat, "berkas": strings.Join(beku, ", ")}))
		return 2
	}

	tujuan := dirFitur
	if o.out != "" {
		tujuan = o.out
	}

	m, err := baca(c, kat, akar, o.tag, o.pkg, feat)
	if err != nil {
		fmt.Fprintln(galat, err)
		return 2
	}
	return tulisModul(m, tujuan, o.apply, keluar, galat)
}

// ── Model ─────────────────────────────────────────────────────────────────────

// modul adalah seluruh yang perlu diketahui untuk memancarkan berkas-berkasnya.
type modul struct {
	c       cfg.Config
	kat     cfg.Katalog
	tag     string // tag kontrak, mis. "buku-tamu"
	pkg     string // paket generated, mis. "bukutamu"
	feature string // direktori feature, mis. "tamu"
	alias   string // alias impor paket generated, mis. "bukutamugen"
	ops     []operasi
}

// operasi adalah satu metode StrictServerInterface, sudah diterjemahkan ke bentuk yang keempat
// template butuhkan.
type operasi struct {
	nama       string // metode Go, mis. "GetKeluargaById"
	rute       string // "GET /keluarga/{id}", dari komentar generator
	respons    string // tipe respons SUKSES, mis. "GetKeluarga200JSONResponse" — dari AST, bukan ditebak
	argumen    []argumen
	hasilWire  string // tipe field Data pada respons; "" bila responsnya tanpa Data
	hasil      konversi
	metaTipe   string // tipe field MetaData bila WAJIB; "" bila opsional/absen
	metaPag    string // tipe field Pagination DI DALAM metaTipe; "" bila metaTipe ""
	adaStatus  bool   // respons punya field Status DAN paket generated punya konstantanya
	adaMessage bool   // respons punya field Message
}

// argumen adalah satu parameter metode store/service, sudah dalam tipe INTERNAL.
type argumen struct {
	nama     string // "id", "params", "body"
	tipe     string // tipe internal, mis. "string", "dtoGetKeluargaParams"
	dariWire string // ekspresi Go yang mengubah request.<Field> jadi tipe internal
}

// konversi menerangkan cara mengubah hasil store (tipe internal) jadi field Data (tipe wire).
type konversi struct {
	tipeInternal string // tipe balik store, mis. "dtoKeluarga", "[]dtoKeluarga", "string"
	keWire       string // ekspresi Go; %s diisi nama variabel hasil
}

// ── Pembacaan ─────────────────────────────────────────────────────────────────

func baca(c cfg.Config, kat cfg.Katalog, akar, tag, pkg, feature string) (modul, error) {
	dirGen := filepath.Join(c.DirGen(akar), pkg)
	berkas, err := filepath.Glob(filepath.Join(dirGen, "*"+c.Go.GenSuffix))
	if err != nil {
		return modul{}, errors.New(kat.T("genmodule.gen_tak_terbaca",
			map[string]string{"jalur": dirGen, "sebab": err.Error(), "tag": tag, "pkg": pkg}))
	}
	if len(berkas) == 0 {
		return modul{}, errors.New(kat.T("genmodule.gen_tak_terbaca",
			map[string]string{"jalur": dirGen, "sebab": "0", "tag": tag, "pkg": pkg}))
	}
	sort.Strings(berkas)

	fset := token.NewFileSet()
	tipe := map[string]*ast.TypeSpec{} // nama tipe -> spec
	konst := map[string]bool{}         // nama konstanta
	var iface *ast.InterfaceType
	for _, f := range berkas {
		af, err := parser.ParseFile(fset, f, nil, parser.ParseComments)
		if err != nil {
			return modul{}, errors.New(kat.T("genmodule.gen_tak_terbaca",
				map[string]string{"jalur": f, "sebab": err.Error(), "tag": tag, "pkg": pkg}))
		}
		for _, d := range af.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, s := range gd.Specs {
				switch sp := s.(type) {
				case *ast.TypeSpec:
					tipe[sp.Name.Name] = sp
					if sp.Name.Name == "StrictServerInterface" {
						iface, _ = sp.Type.(*ast.InterfaceType)
					}
				case *ast.ValueSpec:
					for _, n := range sp.Names {
						konst[n.Name] = true
					}
				}
			}
		}
	}
	if iface == nil {
		return modul{}, errors.New(kat.T("genmodule.tanpa_strict_server",
			map[string]string{"jalur": dirGen}))
	}

	// Cermin privat yang gendto sudah bangkitkan: tipe wire X -> ada dtoX.
	cermin, err := bacaCermin(kat,
		filepath.Join(c.DirFeature(akar), feature, c.NamaBerkasGen("dto_"+pkg)))
	if err != nil {
		return modul{}, err
	}

	m := modul{c: c, kat: kat, tag: tag, pkg: pkg, feature: feature, alias: cfg.AliasGen(pkg)}
	for _, fld := range iface.Methods.List {
		if len(fld.Names) == 0 {
			continue
		}
		op, err := m.bacaOperasi(fld.Names[0].Name, fld, tipe, konst, cermin)
		if err != nil {
			return modul{}, err
		}
		m.ops = append(m.ops, op)
	}
	sort.Slice(m.ops, func(i, j int) bool { return m.ops[i].nama < m.ops[j].nama })
	return m, nil
}

// bacaCermin mengumpulkan nama tipe WIRE yang punya cermin internal, dari tanda tangan
// `func dto<X>FromWire(w <alias>.<X>) dto<X>` yang gendto pancarkan.
//
// Membaca fungsi KONVERTERNYA, bukan nama tipe `dtoX`: kehadiran konverter itulah yang
// menentukan apakah generator boleh menulis ekspresi konversi. Tipe cermin tanpa konverter akan
// menghasilkan Go yang tidak kompilasi, dan itu justru yang harus dihindari.
func bacaCermin(kat cfg.Katalog, jalur string) (map[string]bool, error) {
	out := map[string]bool{}
	src, err := os.ReadFile(jalur)
	if err != nil {
		return out, nil // gendto belum jalan untuk paket ini; seluruh tipe dianggap tak-bercermin
	}
	f, err := parser.ParseFile(token.NewFileSet(), jalur, src, 0)
	if err != nil {
		return nil, errors.New(kat.T("genmodule.cermin_tak_terurai",
			map[string]string{"jalur": jalur, "sebab": err.Error()}))
	}
	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok || fn.Recv != nil {
			continue
		}
		n := fn.Name.Name
		if strings.HasPrefix(n, "dto") && strings.HasSuffix(n, "FromWire") {
			out[strings.TrimSuffix(strings.TrimPrefix(n, "dto"), "FromWire")] = true
		}
	}
	return out, nil
}

func (m modul) bacaOperasi(nama string, fld *ast.Field, tipe map[string]*ast.TypeSpec,
	konst, cermin map[string]bool) (operasi, error) {

	op := operasi{nama: nama, rute: ruteDariKomentar(fld)}

	// Argumen: dari field <nama>RequestObject, urutan apa adanya.
	if spec, ok := tipe[nama+"RequestObject"]; ok {
		if st, _ := spec.Type.(*ast.StructType); st != nil {
			for _, f := range st.Fields.List {
				if len(f.Names) == 0 {
					continue
				}
				op.argumen = append(op.argumen, m.bacaArgumen(f.Names[0].Name, f.Type, tipe, cermin))
			}
		}
	}

	// Tipe respons SUKSES dicari DI ANTARA tipe yang benar-benar ada, bukan dirakit dari
	// "<nama>200JSONResponse". Operasi yang suksesnya 201 atau 204 punya nama lain, dan versi
	// yang merakit namanya memancarkan `var out <alias>.<nama>200JSONResponse` atas tipe yang
	// tidak ada: Go yang SINTAKSISNYA sah, jadi gofmt lolos dan berkasnya mendarat di disk —
	// kegagalannya baru muncul saat build, jauh dari sebabnya.
	op.respons = namaRespons(nama, tipe)
	if op.respons == "" {
		return operasi{}, errors.New(m.kat.T("genmodule.tanpa_respons_sukses",
			map[string]string{"op": nama}))
	}
	st, _ := tipe[op.respons].Type.(*ast.StructType)
	if st == nil {
		return op, nil
	}
	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			continue
		}
		switch f.Names[0].Name {
		case "Status":
			// Konstanta amplop diperiksa DUA arah: field-nya ada di respons ini, DAN paket
			// generated benar-benar mendeklarasikan konstantanya. Tag yang belum opt-in envelope
			// punya salah satunya saja, dan menulis keduanya menghasilkan Go yang tidak kompilasi.
			op.adaStatus = konst[konstStatusSukses]
		case "Message":
			op.adaMessage = true
		case "Data":
			// Alias diselesaikan di sisi respons juga, alasan yang sama dengan sisi argumen: nama
			// alias tidak dicerminkan gendto, jadi tanpa ini tipe wire bocor ke `store`.
			d := selesaikanAlias(f.Type, tipe)
			op.hasilWire = m.renderWire(d)
			op.hasil = m.keInternal(d, cermin)
		case "MetaData":
			// DUA bentuk metaData hidup berdampingan di kontrak, dan hanya satu yang urusan
			// lapis kueri:
			//
			//	MetaData SchemasMetaData   WAJIB — memuat `pagination`. Angkanya (total, page,
			//	                           totalPages) hanya diketahui kueri yang menghitungnya,
			//	                           jadi ia ikut nilai balik store.
			//	MetaData *MetaData         OPSIONAL — kanal metadata umum di samping payload.
			//	                           Tidak diturunkan dari kueri, dan memaksanya masuk tiap
			//	                           tanda tangan store hanya menambah nilai balik mati di
			//	                           mayoritas operasi.
			//
			// Bedanya terbaca dari POINTER-nya, bukan dari nama tipenya: generator memancarkan
			// field wajib sebagai nilai dan opsional sebagai pointer. Jadi aturan ini tetap benar
			// kalau kelak nama tipenya bergeser.
			if _, opsional := f.Type.(*ast.StarExpr); !opsional {
				pag, err := m.bacaTipePaginasi(f.Type, tipe, nama)
				if err != nil {
					return operasi{}, err
				}
				op.metaTipe = m.renderWire(f.Type)
				op.metaPag = pag
			}
		}
	}
	return op, nil
}

// bacaTipePaginasi mengembalikan tipe field `Pagination` DI DALAM metaData wajib, dialias paket
// generated (mis. "keluargagen.Pagination").
//
// Dibutuhkan karena metaData wajib TIDAK mengalir dari store sebagai tipe generated (itu
// melanggar B-01, lihat tandaTangan) — handler yang MENYUSUNNYA dari nilai paginasi platform,
// dan untuk menyusun ia perlu menyebut tipe field dalamnya.
//
// Bentuk yang tak terduga dihentikan NYARING, bukan ditebak: kalau kontrak kelak menambah field
// kedua di metaData wajib, keluaran yang ditebak akan kompilasi di sebagian tag dan gagal di
// sebagian lain — kegagalan yang muncul jauh dari sebabnya.
func (m modul) bacaTipePaginasi(e ast.Expr, tipe map[string]*ast.TypeSpec, op string) (string, error) {
	id, ok := e.(*ast.Ident)
	if !ok {
		return "", errors.New(m.kat.T("genmodule.meta_bukan_ident",
			map[string]string{"op": op, "bentuk": fmt.Sprintf("%T", e)}))
	}
	spec, ok := tipe[id.Name]
	if !ok {
		return "", errors.New(m.kat.T("genmodule.meta_tipe_hilang",
			map[string]string{"op": op, "tipe": id.Name}))
	}
	st, _ := spec.Type.(*ast.StructType)
	if st == nil || len(st.Fields.List) != 1 || len(st.Fields.List[0].Names) != 1 ||
		st.Fields.List[0].Names[0].Name != "Pagination" {
		return "", errors.New(m.kat.T("genmodule.meta_bentuk_lain",
			map[string]string{"op": op, "tipe": id.Name}))
	}
	return m.renderWire(st.Fields.List[0].Type), nil
}

// bacaArgumen menerjemahkan satu field RequestObject jadi parameter store bertipe internal.
func (m modul) bacaArgumen(nama string, e ast.Expr, tipe map[string]*ast.TypeSpec,
	cermin map[string]bool) argumen {

	src := "request." + nama
	lower := strings.ToLower(nama[:1]) + nama[1:]

	// `Body *<Op>JSONRequestBody`, dan JSONRequestBody itu ALIAS ke tipe skema sesungguhnya.
	// Aliasnya diselesaikan supaya cermin internalnya ketemu — gendto melewati nama
	// *JSONRequestBody sebagai plumbing, jadi mencarinya dengan nama itu selalu gagal.
	e = selesaikanAlias(e, tipe)

	// dariWire mengembalikan `src` apa adanya untuk tipe tak-bercermin — jadi kedua kasus
	// (bercermin / tidak) lewat jalur yang sama dan tidak bisa menyimpang.
	k := m.keInternal(e, cermin)
	return argumen{nama: lower, tipe: k.tipeInternal, dariWire: m.dariWire(e, cermin, src)}
}

// maksHop membatasi penelusuran rantai alias. Rantai alias melingkar tidak bisa ada dalam Go
// yang kompilasi, jadi batas ini bukan penanganan kasus nyata melainkan sabuk pengaman supaya
// masukan yang rusak berhenti dengan tipe apa adanya, bukan menggantung.
const maksHop = 16

// selesaikanAlias menelusuri rantai alias tipe sampai ke bentuk sesungguhnya.
//
// Perlu REKURSIF dan perlu menerima target apa pun, bukan cuma *ast.Ident — generator
// memancarkan rantai DUA HOP saat badan request-nya array inline:
//
//	type PostXJSONBody        = []XCreateRequestItem   // hop 2: target SLICE
//	type PostXJSONRequestBody = PostXJSONBody          // hop 1: target Ident
//
// Versi satu-hop/hanya-Ident berhenti di `PostXJSONBody`, yang tidak dicerminkan gendto,
// sehingga tipe WIRE bocor ke `store` — persis lapisan yang interface itu ada untuk
// menjauhkannya.
func selesaikanAlias(e ast.Expr, tipe map[string]*ast.TypeSpec) ast.Expr {
	switch t := e.(type) {
	case *ast.StarExpr:
		return &ast.StarExpr{X: selesaikanAlias(t.X, tipe)}
	case *ast.ArrayType:
		return &ast.ArrayType{Elt: selesaikanAlias(t.Elt, tipe)}
	case *ast.Ident:
		cur := e
		for hop := 0; hop < maksHop; hop++ {
			id, ok := cur.(*ast.Ident)
			if !ok {
				// Target bukan nama: telusuri ke dalamnya (mis. `[]XCreateRequestItem` yang
				// elemennya sendiri bisa alias) lalu selesai.
				return selesaikanAlias(cur, tipe)
			}
			sp, ada := tipe[id.Name]
			if !ada || !sp.Assign.IsValid() {
				return cur // tipe sungguhan, bukan alias — berhenti
			}
			cur = sp.Type
		}
		return cur
	}
	return e
}

// ── Terjemahan tipe ───────────────────────────────────────────────────────────

// renderWire menulis ekspresi tipe sebagaimana ia harus muncul DI LUAR paket generated: nama
// tipe milik paket itu diberi awalan alias, tipe bawaan tidak.
func (m modul) renderWire(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		if tipeBawaan[t.Name] {
			return t.Name
		}
		return m.alias + "." + t.Name
	case *ast.StarExpr:
		return "*" + m.renderWire(t.X)
	case *ast.ArrayType:
		return "[]" + m.renderWire(t.Elt)
	case *ast.MapType:
		return "map[" + m.renderWire(t.Key) + "]" + m.renderWire(t.Value)
	default:
		// mis. openapi_types.UUID / time.Time — sudah berkualifikasi, biarkan.
		return tulisEkspresi(e)
	}
}

// ── Konversi: rekursif atas bentuk tipe, bukan daftar kasus khusus ────────────
//
// Ketiga fungsi di bawah (tipeInternal, fnKeWire, fnDariWire) berjalan pada STRUKTUR tipenya,
// jadi `*[]T`, `[][]T`, dan `map[string][]T` ikut tertangani tanpa satu cabang pun ditambahkan.
// Bentuk sebelumnya menangani tepat tiga kasus dangkal — `T`, `[]T`, `*T` — dan `*[]T` (badan
// request array inline) jatuh ke cabang default: tipe wire bocor ke `store`, diam-diam, tanpa
// satu pun galat kompilasi. Kasus khusus yang dangkal selalu punya kasus keempat.

// tipeInternal menulis tipe yang dipakai `store`/`service`: cermin `dto*` di mana ada, tipe wire
// di mana tidak.
func (m modul) tipeInternal(e ast.Expr, cermin map[string]bool) string {
	switch t := e.(type) {
	case *ast.Ident:
		if cermin[t.Name] {
			return "dto" + t.Name
		}
		return m.renderWire(e)
	case *ast.ArrayType:
		return "[]" + m.tipeInternal(t.Elt, cermin)
	case *ast.StarExpr:
		return "*" + m.tipeInternal(t.X, cermin)
	case *ast.MapType:
		// Kunci map tidak pernah bercermin (kontrak hanya mengizinkan string), nilainya bisa.
		return "map[" + m.renderWire(t.Key) + "]" + m.tipeInternal(t.Value, cermin)
	default:
		return m.renderWire(e)
	}
}

// fnKeWire mengembalikan EKSPRESI FUNGSI Go yang mengubah nilai internal jadi nilai wire, atau
// "" bila tipenya sama di kedua sisi (tak perlu konversi).
func (m modul) fnKeWire(e ast.Expr, cermin map[string]bool) string {
	konv := m.c.PkgDtoconv()
	switch t := e.(type) {
	case *ast.Ident:
		if cermin[t.Name] {
			return fmt.Sprintf("func(v dto%s) %s.%s { return v.toWire() }", t.Name, m.alias, t.Name)
		}
	case *ast.ArrayType:
		if inner := m.fnKeWire(t.Elt, cermin); inner != "" {
			return fmt.Sprintf("func(s %s) %s { return %s.Slice(s, %s) }",
				m.tipeInternal(e, cermin), m.renderWire(e), konv, inner)
		}
	case *ast.StarExpr:
		if inner := m.fnKeWire(t.X, cermin); inner != "" {
			return fmt.Sprintf("func(p %s) %s { return %s.Ptr(p, %s) }",
				m.tipeInternal(e, cermin), m.renderWire(e), konv, inner)
		}
	case *ast.MapType:
		if inner := m.fnKeWire(t.Value, cermin); inner != "" {
			return fmt.Sprintf("func(m %s) %s { return %s.Map(m, %s) }",
				m.tipeInternal(e, cermin), m.renderWire(e), konv, inner)
		}
	}
	return ""
}

// fnDariWire adalah kebalikan fnKeWire: wire -> internal.
func (m modul) fnDariWire(e ast.Expr, cermin map[string]bool) string {
	konv := m.c.PkgDtoconv()
	switch t := e.(type) {
	case *ast.Ident:
		if cermin[t.Name] {
			return "dto" + t.Name + "FromWire" // gendto memancarkannya sebagai fungsi bernama
		}
	case *ast.ArrayType:
		if inner := m.fnDariWire(t.Elt, cermin); inner != "" {
			return fmt.Sprintf("func(s %s) %s { return %s.Slice(s, %s) }",
				m.renderWire(e), m.tipeInternal(e, cermin), konv, inner)
		}
	case *ast.StarExpr:
		if inner := m.fnDariWire(t.X, cermin); inner != "" {
			return fmt.Sprintf("func(p %s) %s { return %s.Ptr(p, %s) }",
				m.renderWire(e), m.tipeInternal(e, cermin), konv, inner)
		}
	case *ast.MapType:
		if inner := m.fnDariWire(t.Value, cermin); inner != "" {
			return fmt.Sprintf("func(m %s) %s { return %s.Map(m, %s) }",
				m.renderWire(e), m.tipeInternal(e, cermin), konv, inner)
		}
	}
	return ""
}

// keInternal memetakan tipe wire ke tipe INTERNAL yang store pakai, plus ekspresi yang mengubah
// nilai internal jadi nilai wire (%s = nama variabel).
//
// Ekspresi diterapkan LANGSUNG di titik pakai untuk bentuk tingkat-atas — `data.toWire()`,
// `<konv>.Slice(data, …)` — bukan lewat pembungkus fungsi, supaya keluarannya tetap terbaca
// seperti kode tulisan tangan. Pembungkus fnKeWire baru muncul di tingkat BERSARANG.
func (m modul) keInternal(e ast.Expr, cermin map[string]bool) konversi {
	k := konversi{tipeInternal: m.tipeInternal(e, cermin)}
	konv := m.c.PkgDtoconv()
	switch t := e.(type) {
	case *ast.Ident:
		if cermin[t.Name] {
			k.keWire = "%s.toWire()"
		}
	case *ast.ArrayType:
		if inner := m.fnKeWire(t.Elt, cermin); inner != "" {
			k.keWire = konv + ".Slice(%s, " + inner + ")"
		}
	case *ast.StarExpr:
		if inner := m.fnKeWire(t.X, cermin); inner != "" {
			k.keWire = konv + ".Ptr(%s, " + inner + ")"
		}
	case *ast.MapType:
		if inner := m.fnKeWire(t.Value, cermin); inner != "" {
			k.keWire = konv + ".Map(%s, " + inner + ")"
		}
	}
	return k
}

// dariWire menulis ekspresi yang mengubah nilai WIRE (`src`) jadi nilai internal — arah
// berlawanan dari konversi.keWire, dipakai untuk argumen masuk.
func (m modul) dariWire(e ast.Expr, cermin map[string]bool, src string) string {
	konv := m.c.PkgDtoconv()
	switch t := e.(type) {
	case *ast.Ident:
		if cermin[t.Name] {
			return fmt.Sprintf("dto%sFromWire(%s)", t.Name, src)
		}
	case *ast.ArrayType:
		if inner := m.fnDariWire(t.Elt, cermin); inner != "" {
			return fmt.Sprintf("%s.Slice(%s, %s)", konv, src, inner)
		}
	case *ast.StarExpr:
		if inner := m.fnDariWire(t.X, cermin); inner != "" {
			return fmt.Sprintf("%s.Ptr(%s, %s)", konv, src, inner)
		}
	case *ast.MapType:
		if inner := m.fnDariWire(t.Value, cermin); inner != "" {
			return fmt.Sprintf("%s.Map(%s, %s)", konv, src, inner)
		}
	}
	return src
}

func tulisEkspresi(e ast.Expr) string {
	var b bytes.Buffer
	_ = format.Node(&b, token.NewFileSet(), e)
	return b.String()
}

// ruteDariKomentar mengambil "GET /keluarga/{id}" dari komentar `// (GET /keluarga/{id})` yang
// generator tulis di atas tiap metode StrictServerInterface. Kosong bila tak ada — itu hanya
// memiskinkan komentar keluaran, tidak mengubah kodenya.
func ruteDariKomentar(fld *ast.Field) string {
	if fld.Doc == nil {
		return ""
	}
	for _, c := range fld.Doc.List {
		s := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if strings.HasPrefix(s, "(") && strings.HasSuffix(s, ")") {
			return s[1 : len(s)-1]
		}
	}
	return ""
}

// ── Pemancaran ────────────────────────────────────────────────────────────────

// header menulis bagian berkas DI ATAS klausa package: penanda mesin plus prosa katalog yang
// menerangkan berkas ini masih boleh ditulis ulang sampai dibekukan.
func (m modul) header(dasar string) string {
	return penandaGenerated + "\n//\n" + cfg.KomentarBlok(m.kat.T("genmodule.komentar.header",
		map[string]string{
			"tag":   m.tag,
			"pkg":   m.pkg,
			"beku":  namaBeku(dasar),
			"gen":   namaBerkas(m.c, dasar),
			"alat":  "genmodule",
			"fitur": m.feature,
		}))
}

// headerRegister menulis SELURUH bagian register.<gen> di atas deklarasi pertamanya: penanda
// generated, prosa headernya, klausa package, dan blok impor.
//
// Ia menerima katalog karena prosa header adalah teks yang ditulis KE DALAM kode proyek target;
// header tanpa prosa akan memindahkan kalimatnya ke tempat yang tidak disentuh uji ini, dan
// itulah kelas cacat yang justru sedang dijaga.
func headerRegister(c cfg.Config, kat cfg.Katalog, tag, pkg, feature string) string {
	m := modul{c: c, kat: kat, tag: tag, pkg: pkg, feature: feature, alias: cfg.AliasGen(pkg)}
	var b strings.Builder
	b.WriteString(m.header("register"))
	fmt.Fprintf(&b, "\npackage %s\n\nimport (\n\t%q\n\t%q\n\n\t%s %q\n)\n", feature,
		impRouter, impORM, m.alias, c.ImportGen(pkg))
	return b.String()
}

func (m modul) register() []byte {
	var b strings.Builder
	b.WriteString(headerRegister(m.c, m.kat, m.tag, m.pkg, m.feature))
	b.WriteString("\n")
	b.WriteString(cfg.KomentarBlok(m.kat.T("genmodule.komentar.register", map[string]string{
		"jumlah": fmt.Sprint(len(m.ops)),
		"tag":    m.tag,
		"alias":  m.alias,
		"router": pkgRouter() + "." + tipeRouter,
		"db":     pkgORM() + "." + tipeDB,
	})))
	fmt.Fprintf(&b, "func Register(public, protected *%s.%s, db *%s.%s) {\n\t_ = db\n"+
		"\t%s.Mount(public, protected, &handler{svc: newService(nil)})\n}\n",
		pkgRouter(), tipeRouter, pkgORM(), tipeDB, m.alias)
	return []byte(b.String())
}

func (m modul) repository() []byte {
	var b strings.Builder
	b.WriteString(m.header("repository"))
	fmt.Fprintf(&b, "\npackage %s\n\nimport (\n\t%q\n", m.feature, m.c.ImportAppcontext())
	if m.adaMetaDiMana() {
		fmt.Fprintf(&b, "\t%q\n", m.c.ImportHttpx())
	}
	b.WriteString(")\n\n")
	b.WriteString(cfg.KomentarBlok(m.kat.T("genmodule.komentar.store", map[string]string{
		"ctx": m.c.PkgAppcontext() + ".AppContext",
	})))
	b.WriteString("type store interface {\n")
	for i, op := range m.ops {
		if i > 0 {
			b.WriteString("\n")
		}
		if op.rute != "" {
			fmt.Fprintf(&b, "\t// %s\n", op.rute)
		}
		fmt.Fprintf(&b, "\t%s\n", m.tandaTangan(op))
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

func (m modul) service() []byte {
	var b strings.Builder
	b.WriteString(m.header("service"))
	fmt.Fprintf(&b, "\npackage %s\n\nimport (\n\t%q\n", m.feature, m.c.ImportAppcontext())
	if m.adaMetaDiMana() {
		fmt.Fprintf(&b, "\t%q\n", m.c.ImportHttpx())
	}
	b.WriteString(")\n\n")
	b.WriteString(cfg.KomentarBlok(m.kat.T("genmodule.komentar.service", nil)))
	b.WriteString("type service struct {\n\tstore store\n}\n\n")
	b.WriteString(cfg.KomentarBlok(m.kat.T("genmodule.komentar.service_new", nil)))
	b.WriteString("func newService(store store) *service { return &service{store: store} }\n")

	for _, op := range m.ops {
		fmt.Fprintf(&b, "\nfunc (s *service) %s {\n\treturn s.store.%s(%s)\n}\n",
			m.tandaTangan(op), op.nama, m.namaArgumen(op))
	}
	return []byte(b.String())
}

func (m modul) handler() []byte {
	var b strings.Builder
	b.WriteString(m.header("handler"))
	fmt.Fprintf(&b, "\npackage %s\n\nimport (\n\t\"context\"\n\n\t%s %q\n\t%q%s\n)\n\n",
		m.feature, m.alias, m.c.ImportGen(m.pkg), m.c.ImportAppcontext(), m.imporConv())
	b.WriteString(cfg.KomentarBlok(m.kat.T("genmodule.komentar.handler", map[string]string{
		"alias": m.alias,
	})))
	b.WriteString("type handler struct{ svc *service }\n\n")
	fmt.Fprintf(&b, "var _ %s.StrictServerInterface = (*handler)(nil)\n\n", m.alias)
	b.WriteString(cfg.KomentarBlok(m.kat.T("genmodule.komentar.handler_ctx", map[string]string{
		"ctx": m.c.PkgAppcontext(),
	})))

	for _, op := range m.ops {
		m.tulisHandler(&b, op)
	}
	return []byte(b.String())
}

func (m modul) tulisHandler(b *strings.Builder, op operasi) {
	fmt.Fprintf(b, "\n%s", cfg.KomentarBlok(m.kat.T("genmodule.komentar.operasi",
		map[string]string{"op": op.nama, "rute": op.rute})))
	fmt.Fprintf(b, "func (h *handler) %s(ctx context.Context, request %s.%sRequestObject) (%s.%sResponseObject, error) {\n",
		op.nama, m.alias, op.nama, m.alias, op.nama)

	args := []string{m.c.PkgAppcontext() + ".From(ctx)"}
	for _, a := range op.argumen {
		args = append(args, a.dariWire)
	}
	panggil := fmt.Sprintf("h.svc.%s(%s)", op.nama, strings.Join(args, ", "))

	if op.hasilWire == "" {
		fmt.Fprintf(b, "\tif err := %s; err != nil {\n\t\treturn nil, err\n\t}\n", panggil)
		fmt.Fprintf(b, "\tvar out %s.%s\n", m.alias, op.respons)
		m.tulisAmplop(b, op)
		b.WriteString("\treturn out, nil\n}\n")
		return
	}

	terima := "data, err :="
	if op.metaTipe != "" {
		terima = "data, pg, err :="
	}
	fmt.Fprintf(b, "\t%s %s\n\tif err != nil {\n\t\treturn nil, err\n\t}\n", terima, panggil)
	fmt.Fprintf(b, "\tvar out %s.%s\n", m.alias, op.respons)
	m.tulisAmplop(b, op)
	if op.hasil.keWire == "" {
		b.WriteString("\tout.Data = data\n")
	} else {
		fmt.Fprintf(b, "\tout.Data = %s\n", fmt.Sprintf(op.hasil.keWire, "data"))
	}
	if op.metaTipe != "" {
		// Penyusunan metaData hidup DI SINI, bukan di store — lihat tandaTangan (B-01).
		fmt.Fprintf(b, "\tout.MetaData = %s{Pagination: %s{Page: pg.Page, Limit: pg.Limit, Total: pg.Total, TotalPages: pg.TotalPages}}\n",
			op.metaTipe, op.metaPag)
	}
	b.WriteString("\treturn out, nil\n}\n")
}

// tulisAmplop mengisi field amplop yang respons ini BENAR-BENAR punya. Kedua field diperiksa
// terpisah: respons 204 tidak punya keduanya, dan tag yang belum opt-in envelope punya Message
// tanpa konstanta Status.
//
// Nilai "Success" sengaja TIDAK dari katalog: ia nilai KABEL yang dibaca klien API, bukan prosa
// untuk pembaca kode. Menerjemahkannya membuat badan respons berubah mengikuti bahasa proyek —
// yaitu kontrak yang berbeda per proyek.
func (m modul) tulisAmplop(b *strings.Builder, op operasi) {
	if op.adaStatus {
		fmt.Fprintf(b, "\tout.Status = %s.%s\n", m.alias, konstStatusSukses)
	}
	if op.adaMessage {
		b.WriteString("\tout.Message = \"Success\"\n")
	}
}

// polaRespons memisahkan nama tipe respons sukses: <Operasi><2xx>[JSON]Response.
var polaRespons = regexp.MustCompile(`^(2\d\d)(JSONResponse|Response)$`)

// namaRespons memilih tipe respons SUKSES sebuah operasi dari tipe yang ada di paket generated:
// status 2xx terkecil, dan pada status yang sama bentuk JSON menang atas bentuk telanjang.
// Mengembalikan "" kalau tak satu pun ada — yang dihentikan pemanggilnya, bukan ditebak.
func namaRespons(op string, tipe map[string]*ast.TypeSpec) string {
	terbaik, kodeTerbaik, jsonTerbaik := "", "", false
	for nama := range tipe {
		sisa, ok := strings.CutPrefix(nama, op)
		if !ok {
			continue
		}
		m := polaRespons.FindStringSubmatch(sisa)
		if m == nil {
			continue
		}
		json := m[2] == "JSONResponse"
		if terbaik == "" || m[1] < kodeTerbaik || (m[1] == kodeTerbaik && json && !jsonTerbaik) {
			terbaik, kodeTerbaik, jsonTerbaik = nama, m[1], json
		}
	}
	return terbaik
}

// tandaTangan menulis "Nama(ctx *<appcontext>.AppContext, ...) (hasil, error)" — sama persis
// untuk store dan service, supaya delegasi service jadi satu baris dan setiap penyimpangan
// antara keduanya jadi galat kompilasi.
//
// # Kenapa paginasi keluar sebagai tipe PLATFORM, bukan tipe generated
//
// Angka paginasi memang hanya diketahui kueri yang menghitungnya, jadi ia HARUS ikut nilai balik
// store. Tapi mengembalikannya dalam tipe GENERATED memaksa lapis kueri dan lapis layanan
// mengimpor paket generated — dan B-01 justru melarang itu: tipe kabel berhenti di handler,
// karena mengetik lapis akses data dengan tipe kontrak HTTP membalik rantai sumber kebenaran.
//
// Tipe paginasi platform punya field yang sama persis dengan Pagination generated, dan lapis
// kueri sudah mengimpor paket platform itu untuk hal lain. Handler yang menyusun metaData dari
// nilai itu — satu baris, di satu-satunya lapis yang memang boleh menyebut tipe generated.
func (m modul) tandaTangan(op operasi) string {
	params := []string{"ctx *" + m.c.PkgAppcontext() + ".AppContext"}
	for _, a := range op.argumen {
		params = append(params, a.nama+" "+a.tipe)
	}
	var hasil []string
	if op.hasilWire != "" {
		hasil = append(hasil, op.hasil.tipeInternal)
	}
	if op.metaTipe != "" {
		hasil = append(hasil, m.c.PkgHttpx()+".Pagination")
	}
	hasil = append(hasil, "error")

	ret := hasil[0]
	if len(hasil) > 1 {
		ret = "(" + strings.Join(hasil, ", ") + ")"
	}
	return fmt.Sprintf("%s(%s) %s", op.nama, strings.Join(params, ", "), ret)
}

func (m modul) namaArgumen(op operasi) string {
	out := []string{"ctx"}
	for _, a := range op.argumen {
		out = append(out, a.nama)
	}
	return strings.Join(out, ", ")
}

// imporConv memancarkan baris impor paket konversi HANYA bila ada operasi yang benar-benar
// memanggilnya. Modul yang seluruh Data-nya bertipe tunggal tidak menyentuh satu pun pembantu
// pemetaan, dan impor tak-terpakai adalah GALAT kompilasi di Go — bukan peringatan.
func (m modul) imporConv() string {
	awalan := m.c.PkgDtoconv() + "."
	for _, op := range m.ops {
		if strings.Contains(op.hasil.keWire, awalan) {
			return fmt.Sprintf("\n\t%q", m.c.ImportDtoconv())
		}
		for _, a := range op.argumen {
			if strings.Contains(a.dariWire, awalan) {
				return fmt.Sprintf("\n\t%q", m.c.ImportDtoconv())
			}
		}
	}
	return ""
}

// adaMetaDiMana melaporkan apakah ADA operasi yang membawa metaData WAJIB — hanya itu yang
// membuat lapis kueri dan lapis layanan perlu mengimpor paket platform paginasi. Impor
// tak-terpakai adalah GALAT kompilasi di Go, jadi impornya kondisional.
//
// MetaData sengaja TIDAK dicerminkan gendto: ia amplop, bukan payload, dan Pagination di
// dalamnya satu tipe yang SAMA di seluruh tag. Mencerminkannya per-fitur akan melahirkan
// salinan tipe amplop yang justru dihindari envelope bersama.
func (m modul) adaMetaDiMana() bool {
	for _, op := range m.ops {
		if op.metaTipe != "" {
			return true
		}
	}
	return false
}

// checklistTenancy memancarkan daftar periksa lintas-penyewa untuk metode store berbentuk
// `(ctx)` atau `(ctx, <string>)` — bentuk baca dan lookup by-ID.
//
// Hanya kedua bentuk itu, dan itu batasan sadar: metode bermuatan (create/update) menulis baris
// saat dijalankan, jadi menjalankannya di uji tanpa penyiapan bukan hal yang bisa
// digeneralisasi. Bentuk `(ctx, id)` justru KELAS YANG PALING SERING BOCOR — id telanjang dari
// path, langsung ke DB, tanpa predikat penyewa (T-02).
//
// # Kenapa PROSA, bukan berkas uji Go yang bisa disalin
//
// Sumber alat ini memancarkan kerangka uji Go yang lengkap. Kerangka itu menyebut tipe store
// konkret, konstruktor konteks penyewa, driver basis data, dan pustaka assertion PROYEK ASALNYA
// — empat API yang standar ini tidak menyatakan dan karena itu tidak bisa mengarangnya. Berkas
// Go yang mengarang API menghasilkan uji yang tidak kompilasi di setiap proyek kecuali satu, dan
// yang menyalinnya akan menyimpulkan alat ini rusak, lalu membuang seluruh berkasnya — termasuk
// bagian yang benar.
//
// Yang bertahan portabel adalah KEWAJIBANNYA: metode mana yang harus diuji, apa yang harus
// di-assert, dan kenapa uji berbasis store tiruan tidak bisa menangkap kelas ini sama sekali.
//
// Mengembalikan nil kalau tak ada metode yang cocok — berkas kosong yang terlihat seperti "sudah
// ditangani" lebih buruk daripada tidak ada berkas.
func (m modul) checklistTenancy() []byte {
	var metode []string
	for _, op := range m.ops {
		bentuk := ""
		switch {
		case len(op.argumen) == 0:
			bentuk = "(ctx)"
		case len(op.argumen) == 1 && op.argumen[0].tipe == "string":
			bentuk = "(ctx, " + op.argumen[0].nama + " string)"
		default:
			continue
		}
		metode = append(metode, m.kat.T("genmodule.tenancy.metode", map[string]string{
			"metode": op.nama,
			"bentuk": bentuk,
			"rute":   op.rute,
		}))
	}
	if len(metode) == 0 {
		return nil
	}
	return []byte(m.kat.T("genmodule.tenancy.checklist", map[string]string{
		"tag":    m.tag,
		"fitur":  m.feature,
		"metode": strings.Join(metode, "\n"),
	}) + "\n")
}

// ── Tulis & bekukan ───────────────────────────────────────────────────────────

func tulisModul(m modul, tujuan string, apply bool, keluar, galat io.Writer) int {
	isi := map[string][]byte{
		"register":   m.register(),
		"handler":    m.handler(),
		"service":    m.service(),
		"repository": m.repository(),
	}

	fmt.Fprintln(keluar, m.kat.T("genmodule.baris_modul", map[string]string{
		"tag":     m.tag,
		"fitur":   m.feature,
		"jumlah":  fmt.Sprint(len(m.ops)),
		"tujuan":  tujuan,
		"berkas1": namaBerkas(m.c, berkasKerangka[0]),
	}))

	type keluaran struct {
		nama string
		src  []byte
	}
	var akanDitulis []keluaran

	for _, dasar := range berkasKerangka {
		nama := namaBerkas(m.c, dasar)
		src, err := format.Source(isi[dasar])
		if err != nil {
			// Keluaran yang tidak bisa diformat = keluaran yang tidak kompilasi. Cetak mentahnya
			// supaya kegagalannya bisa didiagnosis, dan JANGAN tulis ke disk.
			fmt.Fprintf(galat, "\n--- %s ---\n%s\n", nama, isi[dasar])
			fmt.Fprintln(galat, m.kat.T("genmodule.gagal_format",
				map[string]string{"berkas": nama, "sebab": err.Error()}))
			return 2
		}
		fmt.Fprintln(keluar, m.kat.T("genmodule.baris_berkas", map[string]string{
			"berkas": nama,
			"baris":  fmt.Sprint(bytes.Count(src, []byte("\n"))),
		}))
		akanDitulis = append(akanDitulis, keluaran{nama, src})
	}

	// Daftar periksa lintas-penyewa (T-01) — berkas KELIMA, dan sengaja BUKAN kode.
	if mentah := m.checklistTenancy(); mentah != nil {
		fmt.Fprintln(keluar, m.kat.T("genmodule.baris_checklist", map[string]string{
			"berkas": namaChecklistTenancy,
			"baris":  fmt.Sprint(bytes.Count(mentah, []byte("\n"))),
		}))
		akanDitulis = append(akanDitulis, keluaran{namaChecklistTenancy, mentah})
	}

	if !apply {
		// Dry-run: nol tulisan, termasuk nol direktori yang dibuat. Sumber alat ini membuat
		// direktori -out SEBELUM memeriksa -apply, jadi "melaporkan saja" tetap menyentuh disk.
		fmt.Fprintln(keluar, m.kat.T("gen.dry_run", map[string]string{"jumlah": fmt.Sprint(len(akanDitulis))}))
		return 0
	}
	if err := os.MkdirAll(tujuan, 0o755); err != nil {
		fmt.Fprintln(galat, m.kat.T("genmodule.gagal_buat_dir",
			map[string]string{"jalur": tujuan, "sebab": err.Error()}))
		return 2
	}
	for _, k := range akanDitulis {
		jalur := filepath.Join(tujuan, k.nama)
		if err := os.WriteFile(jalur, k.src, 0o644); err != nil {
			fmt.Fprintln(galat, m.kat.T("genmodule.gagal_tulis",
				map[string]string{"jalur": jalur, "sebab": err.Error()}))
			return 2
		}
	}
	return 0
}

// bekukan mengakhiri masa regenerasi sebuah modul: `<dasar><genSuffix>` -> `<dasar>.go`, header
// generator dilucuti.
//
// Sesudah ini generator MENOLAK menyentuh modulnya (deteksi lewat nama berkas), dan itulah
// intinya — yang membekukan bukan catatan di suatu daftar melainkan keadaan direktori itu
// sendiri, yang tidak bisa menyimpang dari kenyataan.
func bekukan(c cfg.Config, kat cfg.Katalog, akar, dirFitur, feat string, apply bool,
	keluar, galat io.Writer) int {

	nama, err := namaDiDirektori(dirFitur)
	if err != nil {
		fmt.Fprintln(galat, kat.T("genmodule.gagal_tulis",
			map[string]string{"jalur": dirFitur, "sebab": err.Error()}))
		return 2
	}
	ada := map[string]bool{}
	for _, n := range nama {
		ada[n] = true
	}

	var dasarAda []string
	for _, dasar := range berkasKerangka {
		if ada[namaBerkas(c, dasar)] {
			dasarAda = append(dasarAda, dasar)
		}
	}
	if len(dasarAda) == 0 {
		fmt.Fprintln(galat, kat.T("genmodule.beku_tanpa_gen",
			map[string]string{"jalur": dirFitur, "sufiks": c.Go.GenSuffix}))
		return 2
	}
	// Tabrakan diperiksa untuk SELURUH berkas sebelum satu pun disentuh: berhenti di tengah
	// meninggalkan modul separuh beku, yang tidak terbaca sebagai keadaan mana pun.
	for _, dasar := range dasarAda {
		if ada[namaBeku(dasar)] {
			fmt.Fprintln(galat, kat.T("genmodule.beku_tabrakan",
				map[string]string{"jalur": filepath.Join(dirFitur, namaBeku(dasar))}))
			return 2
		}
	}

	fmt.Fprintln(keluar, kat.T("genmodule.beku_judul", map[string]string{"jalur": dirFitur}))
	for _, dasar := range dasarAda {
		fmt.Fprintln(keluar, kat.T("genmodule.beku_baris", map[string]string{
			"dari": namaBerkas(c, dasar), "jadi": namaBeku(dasar),
		}))
		if !apply {
			continue
		}
		lama := filepath.Join(dirFitur, namaBerkas(c, dasar))
		src, err := os.ReadFile(lama)
		if err != nil {
			fmt.Fprintln(galat, kat.T("genmodule.gagal_tulis",
				map[string]string{"jalur": lama, "sebab": err.Error()}))
			return 2
		}
		baru := filepath.Join(dirFitur, namaBeku(dasar))
		if err := os.WriteFile(baru, lucutiHeader(src), 0o644); err != nil {
			fmt.Fprintln(galat, kat.T("genmodule.gagal_tulis",
				map[string]string{"jalur": baru, "sebab": err.Error()}))
			return 2
		}
		if err := os.Remove(lama); err != nil {
			fmt.Fprintln(galat, kat.T("genmodule.gagal_tulis",
				map[string]string{"jalur": lama, "sebab": err.Error()}))
			return 2
		}
	}
	if apply {
		fmt.Fprintln(keluar, kat.T("genmodule.beku_sesudah", map[string]string{
			"fitur": feat, "jalur": c.JalurLedgerModul(akar),
		}))
		return 0
	}
	fmt.Fprintln(keluar, kat.T("gen.dry_run", map[string]string{"jumlah": fmt.Sprint(len(dasarAda))}))
	return 0
}

// lucutiHeader membuang blok header generator dari awal berkas. Header itu BERBOHONG sesudah
// pembekuan: berkasnya justru DIMAKSUDKAN untuk disunting sejak saat itu, dan "DO NOT EDIT" yang
// tertinggal akan membuat pembaca berikutnya ragu menyentuh berkas yang memang miliknya.
func lucutiHeader(src []byte) []byte {
	i := bytes.Index(src, []byte("\npackage "))
	if i < 0 {
		return src
	}
	return bytes.TrimLeft(src[i+1:], "\n")
}
