// Code generated by gendto. DO NOT EDIT.
//
// Putar-balik konverter: bukti bahwa pemetaan tidak kehilangan apa pun. Kompilasi hanya
// membuktikan tipenya cocok — bukan bahwa fieldnya terpetakan lengkap. Uji ini mengisi nilai
// kabel dengan nilai bukan-nol sampai ke daun, memutarnya kabel -> cermin -> kabel, lalu
// menuntut DeepEqual. Field yang lupa dipetakan muncul sebagai nilai nol di sisi hasil, dan
// uji ini gagal.

package contoh

import (
	"testing"

	"example.test/fixture/apps/api/internal/platform/dtoconv/dtoconvtest"
)

func TestDtoRoundTrip_Contoh(t *testing.T) {
	t.Run("Contoh", func(t *testing.T) { dtoconvtest.RoundTrip(t, dtoContohFromWire, dtoContoh.toWire) })
	t.Run("ContohCreateRequest", func(t *testing.T) {
		dtoconvtest.RoundTrip(t, dtoContohCreateRequestFromWire, dtoContohCreateRequest.toWire)
	})
	t.Run("ContohMetaData", func(t *testing.T) { dtoconvtest.RoundTrip(t, dtoContohMetaDataFromWire, dtoContohMetaData.toWire) })
	t.Run("GetContohParams", func(t *testing.T) { dtoconvtest.RoundTrip(t, dtoGetContohParamsFromWire, dtoGetContohParams.toWire) })
}
