// Code generated by gendto. DO NOT EDIT.
//
// Cermin PRIVAT dari tipe payload internal/gen/contoh, plus konverter dua arah.
//
// Tanpa tag json dengan sengaja: struct di sini tidak pernah diserialisasi. Yang masuk kabel
// tetap tipe generated (contohgen.*), yang bentuknya ditentukan kontrak. Cermin ini dipakai di
// DALAM paket saja — jadi saat nama tipe generated bergeser, yang perlu dibangkitkan ulang
// hanya berkas ini, bukan tiap handler.
//
// Yang TIDAK dicerminkan, dan itu disengaja:
//   - tipe *RequestObject/*ResponseObject/*JSONResponse — itu seam strict-server, handler
//     wajib mengembalikan tipe generated aslinya;
//   - envelope bersama — ia tunggal, di paket generated bersama;
//   - tipe union oneOf — ia membawa method sendiri di atas json.RawMessage.

package contoh

import (
	"time"

	contohgen "example.test/fixture/apps/api/internal/gen/contoh"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

type dtoContoh struct {
	DibuatPada time.Time
	Id         openapi_types.UUID
	Nama       string
}

func (d dtoContoh) toWire() contohgen.Contoh {
	return contohgen.Contoh{
		DibuatPada: d.DibuatPada,
		Id:         d.Id,
		Nama:       d.Nama,
	}
}

func dtoContohFromWire(w contohgen.Contoh) dtoContoh {
	return dtoContoh{
		DibuatPada: w.DibuatPada,
		Id:         w.Id,
		Nama:       w.Nama,
	}
}

type dtoContohCreateRequest struct {
	Nama string
}

func (d dtoContohCreateRequest) toWire() contohgen.ContohCreateRequest {
	return contohgen.ContohCreateRequest{
		Nama: d.Nama,
	}
}

func dtoContohCreateRequestFromWire(w contohgen.ContohCreateRequest) dtoContohCreateRequest {
	return dtoContohCreateRequest{
		Nama: w.Nama,
	}
}

type dtoContohMetaData struct {
	Pagination contohgen.Pagination
}

func (d dtoContohMetaData) toWire() contohgen.ContohMetaData {
	return contohgen.ContohMetaData{
		Pagination: d.Pagination,
	}
}

func dtoContohMetaDataFromWire(w contohgen.ContohMetaData) dtoContohMetaData {
	return dtoContohMetaData{
		Pagination: w.Pagination,
	}
}

type dtoGetContohParams struct {
	Page  *int
	Limit *int
}

func (d dtoGetContohParams) toWire() contohgen.GetContohParams {
	return contohgen.GetContohParams{
		Page:  d.Page,
		Limit: d.Limit,
	}
}

func dtoGetContohParamsFromWire(w contohgen.GetContohParams) dtoGetContohParams {
	return dtoGetContohParams{
		Page:  w.Page,
		Limit: w.Limit,
	}
}
