// Code generated by genmodule. DO NOT EDIT.
//
// Regen: standard gen module --tag contoh --pkg contoh --apply
//
// Berkas ini masih BOLEH ditulis ulang. Begitu modulnya dikawinkan tangan, bekukan modulnya:
// namanya berubah dari register.gen.go jadi register.go dan generator berhenti menyentuhnya (B-03).

package contoh

import (
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"

	contohgen "example.test/fixture/apps/api/internal/gen/contoh"
)

// Register memasang seluruh 3 operasi tag `contoh` lewat router hasil generate.
//
// Seluruh wiring permission berasal dari kontrak lewat contohgen.Mount: peta permission, rantai
// guard, hook galat, dan daftar path. Implementor hanya menyediakan impl
// contohgen.StrictServerInterface — lihat berkas handler.
//
// Yang TIDAK dijamin Mount: batas penyewa. Itu hidup di predikat kueri dan tidak bisa diturunkan
// dari kontrak (T-01) — ia lahir di lapis kueri tulisan tangan.
//
// # store masih nil, dan itu disengaja
//
// Lapis kueri belum ditulis, jadi tidak ada yang bisa mengisi store-nya. Modul ini kompilasi dan
// ikut boot, tapi setiap operasinya PANIC begitu dipanggil. Itu kegagalan yang NYARING — pilihan
// lain (store tiruan yang mengembalikan kosong) akan membuat modul yang belum berfungsi terlihat
// sehat, dan itu kelas bug yang jauh lebih mahal.
//
// Yang harus dilakukan sesudah lapis kueri ada: ganti `nil` di bawah dengan konstruktor store-mu,
// lalu bekukan modulnya.
//
// # Kalau modul ini butuh dependensi selain koneksi basis data
//
// Bentuk di bawah adalah bentuk POLOS, dan itu yang generator bisa tahu. Modul yang butuh lebih
// (cache, klien penyimpanan objek, kunci tanda tangan, layanan lain) memakai bentuk BERKURI —
// Register mengembalikan fungsi, dan titik masuk aplikasi memanggilnya dengan dependensinya:
//
//	func Register(dep *Dep) func(public, protected *gin.RouterGroup, db *gorm.DB) {
//		return func(_, protected *gin.RouterGroup, db *gorm.DB) {
//			contohgen.Mount(nil, protected, &handler{svc: newService(newStore(db), dep)})
//		}
//	}
//
// Kebutuhan itu TIDAK ADA di kontrak, jadi generator tidak bisa melihatnya — dan itulah salah satu
// dari dua alasan pokok kenapa modul yang sudah dikawinkan tangan tidak boleh digenerate ulang
// (yang kedua: proses tambahan di lapis layanan). Kalau kau mengubah bentuk ini jadi berkuri,
// pemanggilnya di titik masuk aplikasi ikut berubah.
func Register(public, protected *gin.RouterGroup, db *gorm.DB) {
	_ = db
	contohgen.Mount(public, protected, &handler{svc: newService(nil)})
}
