// Code generated by genmodule. DO NOT EDIT.
//
// Regen: standard gen module --tag contoh --pkg contoh --apply
//
// Berkas ini masih BOLEH ditulis ulang. Begitu modulnya dikawinkan tangan, bekukan modulnya:
// namanya berubah dari repository.gen.go jadi repository.go dan generator berhenti menyentuhnya (B-03).

package contoh

import (
	"example.test/fixture/apps/api/internal/platform/appcontext"
	"example.test/fixture/apps/api/internal/platform/httpx"
)

// store adalah kumpulan lengkap operasi basis data yang modul ini butuhkan, satu metode per
// operasi kontrak.
//
// Seluruhnya bertipe INTERNAL (cermin `dto*` dari berkas cermin DTO), bukan tipe generated. Itu
// yang membuat implementornya bebas dari bentuk kabel, dan itu yang B-01 tuntut: saat nama tipe
// generated bergeser, yang perlu dibangkitkan ulang cuma cermin dan handler, bukan setiap kueri.
//
// `ctx *appcontext.AppContext` ADA DI SETIAP metode, termasuk yang cuma menerima id telanjang. Itu bukan hiasan:
// tanpa ctx, implementornya tidak punya cara memasang predikat penyewa, dan id mentah dari path
// langsung dikirim ke basis data — pemegang permission di penyewa A bisa membaca, mengubah, dan
// menghapus baris penyewa B hanya dengan tahu id-nya. T-02 menuntut TANDA TANGANNYA yang diperbaiki,
// bukan pemeriksa pasca-muat yang ditambahkan: pemanggil yang tidak meneruskan konteks harus GAGAL
// KOMPILASI.
type store interface {
	// GET /contoh
	GetContoh(ctx *appcontext.AppContext, params dtoGetContohParams) ([]dtoContoh, httpx.Pagination, error)

	// GET /contoh/{contohId}
	GetContohById(ctx *appcontext.AppContext, contohId string) (dtoContoh, error)

	// POST /contoh
	PostContoh(ctx *appcontext.AppContext, body *dtoContohCreateRequest) (dtoContoh, error)
}
