// Code generated by genmodule. DO NOT EDIT.
//
// Regen: standard gen module --tag contoh --pkg contoh --apply
//
// Berkas ini masih BOLEH ditulis ulang. Begitu modulnya dikawinkan tangan, bekukan modulnya:
// namanya berubah dari service.gen.go jadi service.go dan generator berhenti menyentuhnya (B-03).

package contoh

import (
	"example.test/fixture/apps/api/internal/platform/appcontext"
	"example.test/fixture/apps/api/internal/platform/httpx"
)

// service adalah tempat aturan yang BUKAN bentuk kabel dan BUKAN kueri hidup: guard berbasis
// konteks permintaan, penyuntikan dependensi non-basis-data (notifier, penyimpan berkas, jam), dan
// urutan pemanggilan lintas-store.
//
// Kerangka yang digenerate ini masih delegasi murni — tiap metode meneruskan apa adanya ke store.
// Itu keadaan AWAL yang jujur, bukan bentuk akhirnya: begitu sebuah operasi butuh lebih dari satu
// panggilan store, atau butuh dependensi lain, di sinilah ia ditulis.
//
// Dan itu sekaligus alasan modul yang sudah dikawinkan tangan tidak boleh digenerate ulang:
// generator tidak bisa melihat dependensi yang kau suntikkan ke struct ini.
type service struct {
	store store
}

// newService membuat service di atas store yang diberikan.
//
// Menerima nil: sampai lapis kueri ada, Register menyuntikkan nil — lihat berkas register.
func newService(store store) *service { return &service{store: store} }

func (s *service) GetContoh(ctx *appcontext.AppContext, params dtoGetContohParams) ([]dtoContoh, httpx.Pagination, error) {
	return s.store.GetContoh(ctx, params)
}

func (s *service) GetContohById(ctx *appcontext.AppContext, contohId string) (dtoContoh, error) {
	return s.store.GetContohById(ctx, contohId)
}

func (s *service) PostContoh(ctx *appcontext.AppContext, body *dtoContohCreateRequest) (dtoContoh, error) {
	return s.store.PostContoh(ctx, body)
}
