// Alat gendto — bangkitkan cermin DTO PRIVAT per paket generated, plus konverter dua arah.
//
// Kenapa ada: modul bicara langsung ke tipe di paket generated di ribuan tempat. Saat nama
// tipe generated bergeser (mis. sebuah komponen dipindah ke berkas shared), yang patah bukan
// satu berkas seam melainkan setiap handler. Cermin privat memberi modul nama yang ia miliki
// sendiri; hanya berkas cermin yang menyebut paket generated.
//
// Alat ini membaca AST Go HASIL GENERATE, bukan YAML kontrak, dan itu disengaja: nama tipe Go
// adalah keputusan generator kode, bukan keputusan kontrak. Menurunkannya ulang dari YAML
// berarti menyalin aturan penamaan generator ke berkas ini lalu berharap keduanya tidak
// pernah menyimpang — dan saat menyimpang, yang patah adalah kompilasi setiap modul.
//
// Seluruh module path, direktori, sufiks berkas, nama paket konversi, dan pemetaan paket
// generated -> paket fitur datang dari standard.config.json serta buku besar modul terpasang.
// Tidak ada satu pun literal layout proyek di berkas ini.
//
//	go run ./gendto [-config <jalur>] [-messages <dir>] [-only <pkg>] [-apply]
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"engineering-baseline/tooling/internal/cfg"
)

// kunciDipakai: setiap kunci katalog yang bisa dicetak alat ini, termasuk yang ditulis sebagai
// komentar ke DALAM kode hasil. Diperiksa di muka lewat Katalog.Lengkap.
var kunciDipakai = []string{
	"config.tidak_ditemukan",
	"gen.dry_run",
	"gendto.bendera.apply",
	"gendto.bendera.config",
	"gendto.bendera.messages",
	"gendto.bendera.only",
	"gendto.gagal_tulis",
	"gendto.gagal_urai",
	"gendto.gen_dir_tak_terbaca",
	"gendto.judul_dilewati",
	"gendto.judul_tanpa_fitur",
	"gendto.komentar.berkas",
	"gendto.komentar.dtoconv",
	"gendto.komentar.uji",
	"gendto.ledger_fitur_hilang",
	"gendto.ledger_tabrakan",
	"gendto.ledger_tak_terbaca",
	"gendto.ledger_tanpa_mount",
	"gendto.ledger_tidak_ada",
	"gendto.only_tak_cocok",
	"gendto.only_tanpa_fitur",
	"gendto.pemakaian",
	"gendto.peringatan_format",
	"gendto.baris_paket",
	"gendto.total",
}

// penandaGenerated TIDAK diterjemahkan dan tidak masuk katalog. Ia bukan prosa untuk manusia
// melainkan penanda mesin: gofmt, linter, dan penghitung diff mengenalinya lewat pola tetap
// `^// Code generated .* DO NOT EDIT\.$`. Menerjemahkannya membuat berkas hasil berhenti
// dikenali sebagai generated di setiap alat itu.
const penandaGenerated = "// Code generated by gendto. DO NOT EDIT."

// impOAPI: runtime oapi-codegen, yang wajib dipakai standar ini (lihat batasan global soal
// `go tool oapi-codegen`). Milik toolchain, bukan milik proyek mana pun.
const impOAPI = "github.com/oapi-codegen/runtime/types"

// Plumbing strict-server: bentuk request/response per operasi. Ini justru SEAM-nya — handler
// wajib mengembalikan tipe generated aslinya, jadi mencerminkannya tak ada gunanya.
var plumbing = regexp.MustCompile(`RequestObject$|ResponseObject$|JSONResponse|JSONRequestBody$`)

// Paket yang boleh muncul di tipe PAYLOAD. Apa pun di luar ini (gin, http, context, runtime,
// json, io) menandai tipe INFRASTRUKTUR milik oapi-codegen — bukan bentuk data kontrak.
var payloadPkgs = map[string]bool{"time": true, "openapi_types": true}

// Nama dasar berkas generated yang diperlakukan khusus, tanpa sufiksnya (sufiks dari config):
//   - wiring: pendaftaran rute, tidak memuat tipe payload;
//   - shared: nama di sini adalah ALIAS ke paket generated bersama (envelope), bukan milik tag
//     ini, jadi ia tetap sebagai tipe generated.
const (
	dasarWiring = "wiring"
	dasarShared = "shared"
)

type typeInfo struct {
	name    string
	spec    *ast.TypeSpec
	isAlias bool
	isEnum  bool
	isUnion bool
	isInfra bool
}

type opsi struct {
	config   string
	messages string
	only     string
	apply    bool
}

func main() {
	os.Exit(jalankan(os.Args[1:], os.Stdout, os.Stderr))
}

// jalankan adalah seluruh alat sebagai fungsi murni-cukup untuk diuji: argumen masuk, dua
// aliran keluar, satu kode keluar. main() tidak boleh punya perilaku yang tak bisa disentuh uji.
func jalankan(argv []string, keluar, galat io.Writer) int {
	praConfig, praPesan, bantuan := cfg.PraPindai(argv, benderaBernilai)

	// Bantuan dijawab SEBELUM config dimuat. Alat yang tak bisa menjelaskan dirinya sendiri
	// sebelum dikonfigurasi memaksa orang menebak bendera apa yang ada — dan yang pertama
	// menabraknya adalah orang yang baru memasang paket ini, yang belum punya config.
	if bantuan {
		return cetakBantuan(keluar, galat, praConfig, praPesan)
	}

	c, akar, err := cfg.MuatDari(praConfig)
	if err != nil {
		cfg.LaporGagalConfig(galat, praPesan, err)
		return 2
	}

	kat, err := cfg.MuatKatalogUntuk(praPesan, c.Language)
	if err != nil {
		fmt.Fprintf(galat, cfg.BootstrapKatalog+"\n", err)
		return 2
	}
	if err := kat.Lengkap(kunciDipakai); err != nil {
		fmt.Fprintf(galat, cfg.BootstrapKatalog+"\n", err)
		return 2
	}

	var o opsi
	fs := flag.NewFlagSet("gendto", flag.ContinueOnError)
	fs.SetOutput(galat)
	daftarBendera(fs, &o, kat)
	if err := fs.Parse(argv); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		return 2
	}

	return kerjakan(c, akar, o, kat, keluar, galat)
}

// benderaBernilai: bendera yang memakan argumen berikutnya. Dipakai praPindai supaya nilai
// sebuah bendera tidak salah dibaca sebagai bendera lain — `-only -h` menanyakan paket bernama
// `-h`, bukan bantuan.
var benderaBernilai = map[string]bool{"config": true, "messages": true, "only": true}

func daftarBendera(fs *flag.FlagSet, o *opsi, kat cfg.Katalog) {
	fs.StringVar(&o.config, "config", "", kat.T("gendto.bendera.config", nil))
	fs.StringVar(&o.messages, "messages", "", kat.T("gendto.bendera.messages", nil))
	fs.StringVar(&o.only, "only", "", kat.T("gendto.bendera.only", nil))
	fs.BoolVar(&o.apply, "apply", false, kat.T("gendto.bendera.apply", nil))
}

// cetakBantuan menjawab -h tanpa menuntut config. Kalau config KEBETULAN ketemu, bantuan
// dicetak dalam bahasa proyek itu; kalau tidak, dalam seluruh bahasa katalog — alat yang belum
// dikonfigurasi tidak tahu bahasa siapa yang benar, dan menebak salah satu sama buruknya dengan
// diam.
func cetakBantuan(keluar, galat io.Writer, praConfig, dirPesan string) int {
	bahasa := cfg.BahasaKatalog
	if c, _, err := cfg.MuatDari(praConfig); err == nil && c.Language != "" {
		bahasa = []string{c.Language}
	}
	dicetak := false
	var gagal error
	for _, b := range bahasa {
		kat, err := cfg.MuatKatalogUntuk(dirPesan, b)
		if err != nil {
			if gagal == nil {
				gagal = err
			}
			continue
		}
		if dicetak {
			fmt.Fprintln(keluar)
		}
		var o opsi
		fs := flag.NewFlagSet("gendto", flag.ContinueOnError)
		fs.SetOutput(keluar)
		daftarBendera(fs, &o, kat)
		fmt.Fprintln(keluar, kat.T("gendto.pemakaian", nil))
		fs.PrintDefaults()
		dicetak = true
	}
	if !dicetak {
		// Bantuan pun butuh katalog, karena teks tiap bendera ada di sana. Yang dilaporkan
		// harus SEBABNYA (katalog mana yang tak terbaca), bukan bendera yang diminta.
		fmt.Fprintf(galat, cfg.BootstrapKatalog+"\n", gagal)
		return 2
	}
	return 0
}

func kerjakan(c cfg.Config, akar string, o opsi, kat cfg.Katalog, keluar, galat io.Writer) int {
	dirGen, dirFitur := c.DirGen(akar), c.DirFeature(akar)

	entries, err := os.ReadDir(dirGen)
	if err != nil {
		fmt.Fprintln(galat, kat.T("gendto.gen_dir_tak_terbaca",
			map[string]string{"jalur": dirGen, "sebab": err.Error()}))
		return 2
	}

	peta, catatan, err := muatPetaFitur(c, akar, dirGen, dirFitur, kat)
	if err != nil {
		fmt.Fprintln(galat, err)
		return 2
	}
	for _, baris := range catatan {
		fmt.Fprintln(keluar, baris)
	}

	var (
		totalTipe, totalDilewati, totalDitulis, akanDitulis int
		semuaDilewati, tanpaFitur                           []string
		onlyCocok                                           bool
	)

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pkg := e.Name()
		fitur, ada := fiturUntuk(peta, dirFitur, pkg)

		if o.only != "" {
			if pkg != o.only {
				continue
			}
			onlyCocok = true
			if !ada {
				fmt.Fprintln(galat, kat.T("gendto.only_tanpa_fitur",
					map[string]string{"pkg": pkg, "gen": dirGen}))
				return 2
			}
		}
		if !ada {
			// Dulu ini `continue` diam-diam. Paket generated bersama memang tidak punya fitur
			// senama dan memang tidak boleh dicermin — tapi salah ketik nama direktori terlihat
			// persis sama dari sini, dan sebagai lewatan senyap ia tak pernah muncul di mana pun.
			tanpaFitur = append(tanpaFitur, pkg)
			continue
		}

		src, uji, dilewati, n, err := generate(c, kat, dirGen, pkg, fitur, galat)
		if err != nil {
			fmt.Fprintln(galat, err)
			return 2
		}
		totalTipe += n
		totalDilewati += len(dilewati)
		for _, s := range dilewati {
			semuaDilewati = append(semuaDilewati, pkg+"."+s)
		}
		if n == 0 {
			continue
		}

		berkas := []struct {
			jalur string
			isi   []byte
		}{{filepath.Join(dirFitur, fitur, c.NamaBerkasGen("dto_"+pkg)), src}}
		if uji != nil {
			berkas = append(berkas, struct {
				jalur string
				isi   []byte
			}{filepath.Join(dirFitur, fitur, c.NamaBerkasUjiGen("dto_"+pkg+"_roundtrip")), uji})
		}

		fmt.Fprintln(keluar, kat.T("gendto.baris_paket", map[string]string{
			"pkg":      pkg,
			"berkas":   filepath.Base(berkas[0].jalur),
			"tipe":     fmt.Sprint(n),
			"dilewati": fmt.Sprint(len(dilewati)),
		}))

		akanDitulis += len(berkas)
		if !o.apply {
			continue
		}
		for _, b := range berkas {
			if err := os.WriteFile(b.jalur, b.isi, 0o644); err != nil {
				fmt.Fprintln(galat, kat.T("gendto.gagal_tulis",
					map[string]string{"jalur": b.jalur, "sebab": err.Error()}))
				return 2
			}
			totalDitulis++
		}
	}

	if o.only != "" && !onlyCocok {
		fmt.Fprintln(galat, kat.T("gendto.only_tak_cocok",
			map[string]string{"pkg": o.only, "gen": dirGen}))
		return 2
	}

	if len(tanpaFitur) > 0 {
		sort.Strings(tanpaFitur)
		fmt.Fprintln(keluar)
		fmt.Fprintln(keluar, kat.T("gendto.judul_tanpa_fitur",
			map[string]string{"gen": dirGen, "fitur": dirFitur}))
		for _, s := range tanpaFitur {
			fmt.Fprintln(keluar, "  "+s)
		}
	}
	if len(semuaDilewati) > 0 {
		sort.Strings(semuaDilewati)
		fmt.Fprintln(keluar)
		fmt.Fprintln(keluar, kat.T("gendto.judul_dilewati", nil))
		for _, s := range semuaDilewati {
			fmt.Fprintln(keluar, "  "+s)
		}
	}

	fmt.Fprintln(keluar)
	fmt.Fprintln(keluar, kat.T("gendto.total", map[string]string{
		"tipe":     fmt.Sprint(totalTipe),
		"dilewati": fmt.Sprint(totalDilewati),
		"berkas":   fmt.Sprint(totalDitulis),
	}))
	if !o.apply {
		fmt.Fprintln(keluar, kat.T("gen.dry_run", map[string]string{"jumlah": fmt.Sprint(akanDitulis)}))
	}
	return 0
}

// fiturUntuk menjawab paket fitur pemakai `pkg`, dan apakah `pkg` memang punya cermin.
// Buku besar menang atas nama direktori: ia satu-satunya tempat yang tahu bahwa tag `x-y`
// dipasang di fitur bernama lain. Kalau buku besar diam, aturannya "ada direktori fitur
// senama" — jadi proyek yang namanya sepadan tak perlu mendaftarkan apa pun.
func fiturUntuk(peta map[string]string, dirFitur, pkg string) (string, bool) {
	if f, ok := peta[pkg]; ok {
		return f, true
	}
	if st, err := os.Stat(filepath.Join(dirFitur, pkg)); err == nil && st.IsDir() {
		return pkg, true
	}
	return "", false
}

// muatPetaFitur menurunkan pemetaan paket-generated -> paket-fitur dari buku besar modul
// terpasang, yang mencatat tag -> fitur.
//
// Dulu pemetaan ini adalah map harfiah di dalam alat ini, berisi nama tag proyek asalnya. Itu
// dua cacat sekaligus: nama proyek lain ikut terangkut ke tiap proyek yang memakai standar ini,
// dan tiap tag baru menuntut suntingan alat generasi — yang justru tertutup bagi pelaksana.
func muatPetaFitur(c cfg.Config, akar, dirGen, dirFitur string, kat cfg.Katalog) (map[string]string, []string, error) {
	jalur := c.JalurLedgerModul(akar)

	mentah, err := os.ReadFile(jalur)
	if errors.Is(err, os.ErrNotExist) {
		return map[string]string{}, []string{kat.T("gendto.ledger_tidak_ada", map[string]string{"jalur": jalur})}, nil
	}
	takTerbaca := func(sebab error) error {
		return errors.New(kat.T("gendto.ledger_tak_terbaca",
			map[string]string{"jalur": jalur, "sebab": sebab.Error()}))
	}
	if err != nil {
		return nil, nil, takTerbaca(err)
	}

	var kasar map[string]json.RawMessage
	if err := json.Unmarshal(mentah, &kasar); err != nil {
		return nil, nil, takTerbaca(err)
	}
	mount, ada := kasar["mount"]
	if !ada {
		// Buku besar yang ADA tapi tak berbentuk seperti yang diharapkan tidak boleh diturunkan
		// diam-diam menjadi "tidak ada buku besar": hasilnya cermin yang mendarat di paket fitur
		// yang salah, dan itu baru terlihat saat build.
		return nil, nil, errors.New(kat.T("gendto.ledger_tanpa_mount", map[string]string{"jalur": jalur}))
	}
	var tagKeFitur map[string]string
	if err := json.Unmarshal(mount, &tagKeFitur); err != nil {
		return nil, nil, takTerbaca(err)
	}

	peta := map[string]string{}
	for tag, fitur := range tagKeFitur {
		pkg := pkgGenDariTag(tag)
		if pkg == "" {
			continue
		}
		if lama, bentrok := peta[pkg]; bentrok && lama != fitur {
			return nil, nil, errors.New(kat.T("gendto.ledger_tabrakan", map[string]string{
				"pkg": pkg, "fitur": lama, "lain": fitur, "jalur": jalur,
			}))
		}
		peta[pkg] = fitur
	}

	// Penjaga: entri yang PUNYA direktori generated wajib punya direktori fitur juga. Entri
	// tanpa direktori generated dilewati — tag yang belum opt-in memang belum punya keduanya.
	var rusak []string
	for _, pkg := range kunciTerurut(peta) {
		if st, err := os.Stat(filepath.Join(dirGen, pkg)); err != nil || !st.IsDir() {
			continue
		}
		jf := filepath.Join(dirFitur, peta[pkg])
		if st, err := os.Stat(jf); err != nil || !st.IsDir() {
			rusak = append(rusak, kat.T("gendto.ledger_fitur_hilang",
				map[string]string{"pkg": pkg, "fitur": peta[pkg], "jalur": jf}))
		}
	}
	if len(rusak) > 0 {
		return nil, nil, errors.New(strings.Join(rusak, "\n"))
	}
	return peta, nil, nil
}

// pkgGenDariTag menurunkan nama paket generated dari nama tag kontrak: huruf kecil, tanpa
// pemisah. Aturan yang sama dipakai generator kode saat memilih nama paket, dan itulah
// alasannya tidak ada kunci config ketiga untuk hubungan ini.
func pkgGenDariTag(tag string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(tag) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func kunciTerurut(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func generate(c cfg.Config, kat cfg.Katalog, dirGen, pkg, fitur string, galat io.Writer) ([]byte, []byte, []string, int, error) {
	fset := token.NewFileSet()
	files, err := filepath.Glob(filepath.Join(dirGen, pkg, "*"+c.Go.GenSuffix))
	if err != nil {
		return nil, nil, nil, 0, err
	}
	sort.Strings(files)

	types := map[string]*typeInfo{}
	var order []string
	// Nama yang lahir di berkas shared adalah ALIAS ke paket generated bersama (envelope).
	// Ia bukan milik tag ini; biarkan tetap sebagai tipe generated.
	sharedAliases := map[string]bool{}

	for _, f := range files {
		base := filepath.Base(f)
		if base == c.NamaBerkasGen(dasarWiring) {
			continue
		}
		af, err := parser.ParseFile(fset, f, nil, 0)
		if err != nil {
			return nil, nil, nil, 0, errors.New(kat.T("gendto.gagal_urai",
				map[string]string{"jalur": f, "sebab": err.Error()}))
		}
		for _, d := range af.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, s := range gd.Specs {
				ts := s.(*ast.TypeSpec)
				name := ts.Name.Name
				if base == c.NamaBerkasGen(dasarShared) {
					sharedAliases[name] = true
					continue
				}
				if plumbing.MatchString(name) || !ts.Name.IsExported() {
					continue
				}
				ti := &typeInfo{name: name, spec: ts, isAlias: ts.Assign.IsValid()}
				switch t := ts.Type.(type) {
				case *ast.Ident:
					ti.isEnum = isBasic(t.Name)
				case *ast.StructType:
					for _, fl := range t.Fields.List {
						if len(fl.Names) == 1 && fl.Names[0].Name == "union" {
							ti.isUnion = true
						}
					}
				case *ast.FuncType, *ast.InterfaceType:
					ti.isInfra = true
				}
				if referencesForeignPkg(ts.Type) {
					ti.isInfra = true
				}
				types[name] = ti
				order = append(order, name)
			}
		}
	}
	sort.Strings(order)

	var dilewati []string
	mirror := map[string]bool{}
	for _, n := range order {
		ti := types[n]
		switch {
		case ti.isUnion:
			dilewati = append(dilewati, n)
		case ti.isInfra, sharedAliases[n]:
			// diam-diam dilewati: infrastruktur oapi-codegen / envelope bersama
		case ti.isAlias && isSharedIdent(ti.spec.Type, sharedAliases):
			// type Failure = FailureEnvelope
		default:
			mirror[n] = true
		}
	}
	if len(mirror) == 0 {
		return nil, nil, dilewati, 0, nil
	}

	g := &gen{
		pkg:        pkg,
		alias:      cfg.AliasGen(pkg),
		pkgConv:    c.PkgDtoconv(),
		impGen:     c.ImportGen(pkg),
		impConv:    c.ImportDtoconv(),
		impConvUji: c.ImportDtoconvTest(),
		types:      types,
		mirror:     mirror,
	}
	var b bytes.Buffer
	for _, n := range order {
		if mirror[n] {
			g.emit(&b, types[n])
		}
	}

	var head bytes.Buffer
	head.WriteString(penandaGenerated + "\n//\n")
	head.WriteString(cfg.KomentarBlok(kat.T("gendto.komentar.berkas", map[string]string{
		"gen":   path.Join(c.Go.GenDir, pkg),
		"alias": g.alias,
	})))
	fmt.Fprintf(&head, "\npackage %s\n\n", fitur)
	if g.needConv {
		head.WriteString(cfg.KomentarBlok(kat.T("gendto.komentar.dtoconv", map[string]string{
			"pkgKonv":   g.pkgConv,
			"jalurKonv": c.Go.DtoconvPkg,
		})))
		head.WriteString("\n")
	}
	fmt.Fprintf(&head, "import (\n%s)\n\n", g.imports())
	head.Write(b.Bytes())

	out := rapikan(head.Bytes(), kat, pkg, galat)
	uji := berkasPutarBalik(c, kat, pkg, fitur, order, mirror, types, galat)
	return out, uji, dilewati, len(mirror), nil
}

// rapikan menjalankan gofmt atas keluaran. Kalau gagal, berkas tetap ditulis apa adanya dan
// kegagalannya DILAPORKAN: keluaran tak terformat masih bisa dibaca manusia dan diperbaiki,
// sedangkan menelan galatnya membuat berkas rusak mendarat tanpa jejak.
func rapikan(isi []byte, kat cfg.Katalog, pkg string, galat io.Writer) []byte {
	out, err := format.Source(isi)
	if err != nil {
		fmt.Fprintln(galat, kat.T("gendto.peringatan_format",
			map[string]string{"pkg": pkg, "sebab": err.Error()}))
		return isi
	}
	return out
}

func isSharedIdent(e ast.Expr, shared map[string]bool) bool {
	id, ok := e.(*ast.Ident)
	return ok && shared[id.Name]
}

// referencesForeignPkg: benar kalau tipe menyentuh paket di luar daftar payload (gin, http,
// context, runtime, ...). Itu penanda tipe infrastruktur, bukan bentuk data kontrak.
func referencesForeignPkg(e ast.Expr) bool {
	found := false
	ast.Inspect(e, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok && !payloadPkgs[id.Name] {
				found = true
			}
		}
		return true
	})
	return found
}

type gen struct {
	pkg        string
	alias      string
	pkgConv    string
	impGen     string
	impConv    string
	impConvUji string
	types      map[string]*typeInfo
	mirror     map[string]bool
	needTime   bool
	needOAPI   bool
	needConv   bool
}

// berkasPutarBalik: bukti bahwa konverter TIDAK kehilangan apa pun. Kompilasi hanya membuktikan
// tipenya cocok — bukan bahwa fieldnya terpetakan lengkap. Uji ini mengisi nilai kabel dengan
// nilai bukan-nol sampai ke daun, memutarnya kabel->cermin->kabel, lalu menuntut DeepEqual.
func berkasPutarBalik(c cfg.Config, kat cfg.Katalog, pkg, fitur string, order []string,
	mirror map[string]bool, types map[string]*typeInfo, galat io.Writer) []byte {

	var b bytes.Buffer
	b.WriteString(penandaGenerated + "\n//\n")
	b.WriteString(cfg.KomentarBlok(kat.T("gendto.komentar.uji", nil)))
	fmt.Fprintf(&b, "\npackage %s\n\nimport (\n\t\"testing\"\n\n\t%q\n)\n\n", fitur, c.ImportDtoconvTest())
	fmt.Fprintf(&b, "func TestDtoRoundTrip_%s(t *testing.T) {\n", judul(pkg))

	pkgUji := path.Base(c.ImportDtoconvTest())
	n := 0
	for _, name := range order {
		if !mirror[name] || types[name].isAlias {
			continue
		}
		p := priv(name)
		fmt.Fprintf(&b, "\tt.Run(%q, func(t *testing.T) { %s.RoundTrip(t, %sFromWire, %s.toWire) })\n",
			name, pkgUji, p, p)
		n++
	}
	b.WriteString("}\n")
	if n == 0 {
		return nil
	}
	return rapikan(b.Bytes(), kat, pkg, galat)
}

// judul menjadikan nama paket sebuah identifier Go yang sah untuk nama fungsi uji.
func judul(pkg string) string {
	var b strings.Builder
	naik := true
	for _, r := range pkg {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			if naik {
				b.WriteRune(unicode.ToUpper(r))
				naik = false
				continue
			}
			b.WriteRune(r)
		default:
			naik = true
		}
	}
	return b.String()
}

func (g *gen) imports() string {
	var s []string
	if g.needTime {
		s = append(s, "\t\"time\"\n\n")
	}
	if g.needOAPI {
		s = append(s, fmt.Sprintf("\topenapi_types %q\n", impOAPI))
	}
	// Impor paket konversi KONDISIONAL: paket cermin tanpa slice/map/pointer bersarang tidak
	// memanggilnya sama sekali, dan impor tak-terpakai adalah galat kompilasi di Go.
	if g.needConv {
		s = append(s, fmt.Sprintf("\t%q\n", g.impConv))
	}
	s = append(s, fmt.Sprintf("\t%s %q\n", g.alias, g.impGen))
	return strings.Join(s, "")
}

// priv memberi nama cermin: prefiks `dto` + nama generated.
//
// Prefiks, bukan sufiks: kode tulisan tangan lazim memakai sufiks `DTO`, jadi sufiks akan
// bertabrakan. Prefiks juga menjamin huruf pertama kecil = privat.
func priv(n string) string { return "dto" + n }

func (g *gen) emit(b *bytes.Buffer, ti *typeInfo) {
	n, p := ti.name, priv(ti.name)

	if ti.isAlias {
		fmt.Fprintf(b, "type %s = %s\n\n", p, g.mirrorStr(ti.spec.Type))
		return
	}
	if ti.isEnum {
		fmt.Fprintf(b, "type %s %s\n\n", p, g.mirrorStr(ti.spec.Type))
		fmt.Fprintf(b, "func (d %s) toWire() %s.%s { return %s.%s(d) }\n\n", p, g.alias, n, g.alias, n)
		fmt.Fprintf(b, "func %sFromWire(w %s.%s) %s { return %s(w) }\n\n", p, g.alias, n, p, p)
		return
	}
	st, ok := ti.spec.Type.(*ast.StructType)
	if !ok {
		fmt.Fprintf(b, "type %s %s\n\n", p, g.mirrorStr(ti.spec.Type))
		return
	}

	fields := exported(st)
	fmt.Fprintf(b, "type %s struct {\n", p)
	for _, f := range fields {
		fmt.Fprintf(b, "\t%s %s\n", f.name, g.mirrorStr(f.typ))
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "func (d %s) toWire() %s.%s {\n\treturn %s.%s{\n", p, g.alias, n, g.alias, n)
	for _, f := range fields {
		fmt.Fprintf(b, "\t\t%s: %s,\n", f.name, g.conv("d."+f.name, f.typ, true))
	}
	b.WriteString("\t}\n}\n\n")

	fmt.Fprintf(b, "func %sFromWire(w %s.%s) %s {\n\treturn %s{\n", p, g.alias, n, p, p)
	for _, f := range fields {
		fmt.Fprintf(b, "\t\t%s: %s,\n", f.name, g.conv("w."+f.name, f.typ, false))
	}
	b.WriteString("\t}\n}\n\n")
}

type field struct {
	name string
	typ  ast.Expr
}

func exported(st *ast.StructType) []field {
	var out []field
	for _, f := range st.Fields.List {
		for _, nm := range f.Names {
			if nm.IsExported() {
				out = append(out, field{nm.Name, f.Type})
			}
		}
	}
	return out
}

// mirrorStr: tipe versi CERMIN (nama yang dicerminkan -> nama privat).
func (g *gen) mirrorStr(e ast.Expr) string { return g.str(e, true) }

// wireStr: tipe versi GENERATED (nama yang dicerminkan -> alias.Nama).
func (g *gen) wireStr(e ast.Expr) string { return g.str(e, false) }

func (g *gen) str(e ast.Expr, asMirror bool) string {
	switch t := e.(type) {
	case *ast.Ident:
		if g.mirror[t.Name] {
			if asMirror {
				return priv(t.Name)
			}
			return g.alias + "." + t.Name
		}
		if isBuiltin(t.Name) {
			return t.Name
		}
		// Tipe milik paket generated yang tidak dicerminkan (union, envelope bersama).
		// Wajib berkualifikasi — tanpa ini ia jadi identifier tak dikenal di paket fitur.
		return g.alias + "." + t.Name
	case *ast.StarExpr:
		return "*" + g.str(t.X, asMirror)
	case *ast.ArrayType:
		return "[]" + g.str(t.Elt, asMirror)
	case *ast.MapType:
		return "map[" + g.str(t.Key, asMirror) + "]" + g.str(t.Value, asMirror)
	case *ast.SelectorExpr:
		pkgName := t.X.(*ast.Ident).Name
		if pkgName == "time" {
			g.needTime = true
		}
		if pkgName == "openapi_types" {
			g.needOAPI = true
		}
		return pkgName + "." + t.Sel.Name
	case *ast.InterfaceType:
		return "any"
	}
	return "any"
}

// hasMirror: apakah ada tipe yang dicerminkan di dalam ekspresi tipe ini? Kalau tidak,
// konversinya identitas dan tak perlu dibungkus apa pun.
func (g *gen) hasMirror(e ast.Expr) bool {
	found := false
	ast.Inspect(e, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok && g.mirror[id.Name] {
			found = true
		}
		return true
	})
	return found
}

// conv membangun ekspresi konversi satu field. toWire=true: cermin -> generated.
func (g *gen) conv(src string, e ast.Expr, toWire bool) string {
	if !g.hasMirror(e) {
		return src
	}
	switch t := e.(type) {
	case *ast.Ident:
		if g.types[t.Name].isEnum {
			if toWire {
				return fmt.Sprintf("%s.%s(%s)", g.alias, t.Name, src)
			}
			return fmt.Sprintf("%s(%s)", priv(t.Name), src)
		}
		if toWire {
			return src + ".toWire()"
		}
		return priv(t.Name) + "FromWire(" + src + ")"

	case *ast.StarExpr:
		// Pointer ke tipe beralas sama boleh dikonversi langsung — tanpa alokasi, dan nil
		// tetap nil.
		if id, ok := t.X.(*ast.Ident); ok && g.types[id.Name].isEnum {
			if toWire {
				return fmt.Sprintf("(*%s.%s)(%s)", g.alias, id.Name, src)
			}
			return fmt.Sprintf("(*%s)(%s)", priv(id.Name), src)
		}
		g.needConv = true
		return fmt.Sprintf("%s.Ptr(%s, %s)", g.pkgConv, src, g.fn(t.X, toWire))

	case *ast.ArrayType:
		g.needConv = true
		return fmt.Sprintf("%s.Slice(%s, %s)", g.pkgConv, src, g.fn(t.Elt, toWire))

	case *ast.MapType:
		g.needConv = true
		return fmt.Sprintf("%s.Map(%s, %s)", g.pkgConv, src, g.fn(t.Value, toWire))
	}
	return src
}

// fn menghasilkan ekspresi bertipe func(A) B untuk elemen sebuah slice/pointer/map.
func (g *gen) fn(e ast.Expr, toWire bool) string {
	// Kasus lazim: elemen adalah struct yang dicerminkan -> pakai method expression /
	// fungsi FromWire langsung, tanpa closure.
	if id, ok := e.(*ast.Ident); ok && g.mirror[id.Name] && !g.types[id.Name].isEnum {
		if toWire {
			return priv(id.Name) + ".toWire"
		}
		return priv(id.Name) + "FromWire"
	}
	from, to := g.mirrorStr(e), g.wireStr(e)
	if !toWire {
		from, to = to, from
	}
	return fmt.Sprintf("func(v %s) %s { return %s }", from, to, g.conv("v", e, toWire))
}

func isBuiltin(n string) bool {
	switch n {
	case "string", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16",
		"uint32", "uint64", "float32", "float64", "bool", "byte", "rune", "any", "error":
		return true
	}
	return false
}

func isBasic(n string) bool {
	switch n {
	case "string", "int", "int32", "int64", "float32", "float64", "bool":
		return true
	}
	return false
}
